### ISSUE TITLE
KeyDB with StackExchange .NET Client

### ISSUE THREAD

**Issue by khaledobaid** [JohnSully/KeyDB#104] opened 2019-11-12 16:59 UTC
I'm connecting two active-replica nodes with ASP.NET core application and using KeyDB as distributed cache back-end.

I 'm using StackExchange Redis Client for .NET, to connect to the KeyDB and It Is Working, however i noticed that storing binary data using HashSet cause an issue. the values are not being replicated to the other node.

Note that everything else is working perfectly :
1. String Set (string)
2. String Set (bytes) / Some values will not be replicated
3. Hash Set (string values)
4. Hash Set (Binary : Data Only Appear on the Original Server )

Issue only happen when i try to store binary data in specific hash entry.

Sample Code using StackExchange

byte[] bytes;
var obj = new Name() { Prop1 = 1, Prop2 = "Khaled" };

using (var stream = new MemoryStream())
{
new BinaryFormatter().Serialize(stream, obj);
bytes = stream.ToArray();
}

HashEntry[] hashEntries = new HashEntry[2];
hashEntries[0] = new HashEntry("prop1", bytes);
hashEntries[1] = new HashEntry("prop2", "string value");

db.HashSet("hashset", hashEntries);

//db.StringSet("BINDATA", bytes); // This will work !

[Serializable]
public class Name
{
public int Prop1 { get; set; }
public string Prop2 { get; set; }
}

**Comment by JohnSully** [comment] 2019-11-12 21:59
Hi @khaledobaid 

Thanks for the sample code, I will try to repro and get back to you.

**Comment by khaledobaid** [comment] 2019-11-13 05:15
BTW, some simple db.StringSet for byte[] will also fail,if the value is not binary-safe.

**Comment by JohnSully** [comment] 2019-11-21 01:24
@khaledobaid What version of KeyDB are you running?  I cannot repro this issue with your sample code.  We did have a bug #64 very early on with active replication but this has been fixed since v5.0

**Comment by JohnSully** [comment] 2019-11-21 01:26
Closing as dupe of #64.  If you are using a version >=5.0 let me know and I'll reopen.

**Closed by JohnSully** 2019-11-21 01:26 UTC

**Comment by khaledobaid** [comment] 2019-11-25 07:01
Thanks @JohnSully  I'll check and let you know.

**Comment by khaledobaid** [comment] 2019-11-27 15:55
Hello, it seems i have old version (KeyDB 0.9.6 (72c49130/0) 64 bit)
I'll upgrade and let you know if the issue still exists

**Comment by khaledobaid** [comment] 2019-11-27 17:43
Confirming that update to 5.1.1 (unstable) fixed the issue !

**Comment by JohnSully** [comment] 2019-11-27 17:50
Glad to hear it!  Thanks for the bug report.
