### ISSUE TITLE
== CRITICAL ==

### ISSUE THREAD

**Issue by Talkabout** [JohnSully/KeyDB#143] opened 2020-02-17 07:11 UTC
Hi guys,

I have checked the system log of both keydb servers I am running (active replica) and they are giving me the following error multiple times per minute:

== CRITICAL == This replica is sending an error to its master: 'unknown command `304769`, with args beginning with: ' after processing the command '<unknown>'

what exactly does that mean?

Thanks!

Bye

**Comment by JohnSully** [comment] 2020-02-19 02:25
Odd,

Are you mixing KeyDB versions or replicating with Redis?  Unfortunately the error message is not very illuminating, I’ll make it more verbose in a future version. 

It would be helpful if you could give the output of the monitor command around the time you see this message. The missing piece is the command the replica is sending.

**Comment by Talkabout** [comment] 2020-02-19 07:09
Hi @JohnSully ,

same KeyDB version, no Redis.

The error message is coming multiple times per minute, so shouldn't be a problem to get more information. What exact command do I need to execute? Simply "MONITOR" on keydb-cli?

Bye

**Comment by JohnSully** [comment] 2020-02-19 23:28
You can run it like this:
`./keydb-cli -h 127.0.0.1 -p 6379 monitor > out.txt`
Change the IP and port as necessary, it should be of the replica showing the error.

once you have some data captured we can filter out uninteresting traffic with
`grep "[IP of master]" out.txt > filter.txt`
e.g.
`grep "127.0.0.1" out.txt > filter.txt`

Then it's just a matter of matching the timeframes.  The monitor command outputs timestamps in unix time, while the KeyDB log will show time in normally.  You can translate back and forth with this: https://www.unixtimestamp.com/index.php

e.g. 1582154414.789113 is 02/19/2020 @ 11:20pm (UTC)

**Comment by Antiarchitect** [comment] 2020-03-02 13:59
Having similar issue:
```
1:S 02 Mar 2020 13:57:46.769 # == CRITICAL == This replica is sending an error to its master: 'EXEC without MULTI' after processing the command 'exec'
1:S 02 Mar 2020 13:57:46.827 # == CRITICAL == This replica is sending an error to its master: 'MULTI calls can not be nested' after processing the command 'multi'
1:S 02 Mar 2020 13:57:46.828 # == CRITICAL == This replica is sending an error to its master: 'EXEC without MULTI' after processing the command 'exec'
1:S 02 Mar 2020 13:57:48.801 # == CRITICAL == This replica is sending an error to its master: 'EXEC without MULTI' after processing the command 'exec'
1:S 02 Mar 2020 13:57:48.801 # == CRITICAL == This replica is sending an error to its master: 'MULTI calls can not be nested' after processing the command 'multi'
1:S 02 Mar 2020 13:57:48.853 # == CRITICAL == This replica is sending an error to its master: 'MULTI calls can not be nested' after processing the command 'multi'
1:S 02 Mar 2020 13:57:48.853 # == CRITICAL == This replica is sending an error to its master: 'EXEC without MULTI' after processing the command 'exec'
1:S 02 Mar 2020 13:58:08.462 # == CRITICAL == This replica is sending an error to its master: 'MULTI calls can not be nested' after processing the command 'multi'
1:S 02 Mar 2020 13:58:08.462 # == CRITICAL == This replica is sending an error to its master: 'EXEC without MULTI' after processing the command 'exec'
1:S 02 Mar 2020 13:58:08.563 # == CRITICAL == This replica is sending an error to its master: 'EXEC without MULTI' after processing the command 'exec'
1:S 02 Mar 2020 13:58:08.790 # == CRITICAL == This replica is sending an error to its master: 'MULTI calls can not be nested' after processing the command 'multi'
1:S 02 Mar 2020 13:58:08.791 # == CRITICAL == This replica is sending an error to its master: 'EXEC without MULTI' after processing the command 'exec'
1:S 02 Mar 2020 13:58:18.771 # == CRITICAL == This replica is sending an error to its master: 'MULTI calls can not be nested' after processing the command 'multi'
1:S 02 Mar 2020 13:58:18.771 # == CRITICAL == This replica is sending an error to its master: 'EXEC without MULTI' after processing the command 'exec'
```

**Comment by JohnSully** [comment] 2020-03-03 19:42
Thank you!  I've reworked the way transactions are handled during active replication in v5.3.2 (just released).  It would be good if you could give that a try as I think it will resolve your issue.

**Comment by Talkabout** [comment] 2020-03-03 19:44
Hi @JohnSully ,

both issues or only one of them? The error messages are similar but not same.

Bye

**Comment by JohnSully** [comment] 2020-03-03 19:48
Hi @Talkabout 

I'm less certain it will fix your issue (although it still may).  If you get a chance to pass on the monitor output from around the time it repros that would be helpful in letting me better understand what's causing the error your seeing.

**Comment by Antiarchitect** [comment] 2020-03-03 20:14
> Thank you! I've reworked the way transactions are handled during active replication in v5.3.2 (just released). It would be good if you could give that a try as I think it will resolve your issue.

Actually I'm still experiencing this in 5.3.2. When I've fixed my replication in the chart - there less records than before. But messages are still present. I'm using KeyDB multi-master in the Sentry chart (maybe bad code?). If I can help you with my logs or debug - please tell me what to do. With redis-ha chart (master-slave) - there were no errors of this kind - I've checked old logs.

**Comment by JohnSully** [comment] 2020-03-03 20:58
@Antiarchitect @Talkabout 

I appreciate your help with tracking this down. The best way forward will be for me to update the logging to give me more information. That way you won’t have to mess with monitor or other logs. 

I will update this bug when the new logging is added.

**Comment by Antiarchitect** [comment] 2020-03-03 21:13
Got it!

**Comment by JohnSully** [comment] 2020-03-05 04:18
@Antiarchitect @Talkabout 

I've added extra logging, primarily around what exactly is in the query buffer when the error occurs.  The docker images have been updated and the v5.3.2 tag has also been modified to include this change.  I did not bump the version as it's only a logging change and 5.3.2 was just released.

**Comment by Antiarchitect** [comment] 2020-03-05 09:14
Will try to update today

**Comment by Antiarchitect** [comment] 2020-03-05 16:23
```
7:S 05 Mar 2020 16:21:35.511 # == CRITICAL == This replica is sending an error to its master: 'EXEC without MULTI' after processing the command 'exec'
7:S 05 Mar 2020 16:21:35.511 #  querybuf: *1\r\n$4\r\nEXEC\r\n
7:S 05 Mar 2020 16:21:35.511 # == CRITICAL == This replica is sending an error to its master: 'Error in rreplay command, please check logs' after processing the command 'rreplay'
7:S 05 Mar 2020 16:21:35.511 #  querybuf: $1\r\n0\r\n$19\r\n1660341762582908496\r\n*5\r\n$7\r\nRREPLAY\r\n$36\r\n12f895d6-ed18-4acd-96fd-0f018402e3e0\r\n$14\r\n*1\r\n$4\r\nEXEC\r\n\r\n$1\r\n0\r\n$19\r\n1660341762582908497\r\n
7:S 05 Mar 2020 16:21:43.201 # == CRITICAL == This replica is sending an error to its master: 'EXEC without MULTI' after processing the command 'exec'
7:S 05 Mar 2020 16:21:43.201 #  querybuf: *1\r\n$4\r\nEXEC\r\n
7:S 05 Mar 2020 16:21:43.201 # == CRITICAL == This replica is sending an error to its master: 'Error in rreplay command, please check logs' after processing the command 'rreplay'
7:S 05 Mar 2020 16:21:43.201 #  querybuf: *5\r\n$7\r\nRREPLAY\r\n$36\r\n12f895d6-ed18-4acd-96fd-0f018402e3e0\r\n$15\r\n*1\r\n$5\r\nMULTI\r\n\r\n$1\r\n0\r\n$19\r\n1660341770705174999\r\n*5\r\n$7\r\nRREPLAY\r\n$36\r\n12f895d6-ed18-4acd-96fd-0f018402e3e0\r\n$77\r\n*3\r\n$4\r\nZREM\r\n$13\r\nunacked_index\r\n$36\r\n7a5a8d38-a30f-487e-9b39-5d9537ab195f\r\n\r\n$1\r\n0\r\n$19\r\n1660341770705175000\r\n*5\r\n$7\r\nRREPLAY\r\n$36\r\n12f895d6-ed18-4acd-96fd-0f018402e3e0\r\n$70\r\n*3\r\n$4\r\nHDEL\r\n$7\r\nunacked\r\n$36\r\n7a5a8d38-a30f-487e-9b39-5d9537ab195f\r\n\r\n$1\r\n0\r\n$19\r\n1660341770705175001\r\n*5\r\n$7\r\nRREPLAY\r\n$36\r\n12f895d6-ed18-4acd-96fd-0f018402e3e0\r\n$14\r\n*1\r\n$4\r\nEXEC\r\n\r\n$1\r\n0\r\n$19\r\n1660341770705175002\r\n*5\r\n$7\r\nRREPLAY\r\n$36\r\n12f895d6-ed18-4acd-96fd-0f018402e3e0\r\n$211\r\n*5\r\n$7\r\nRREPLAY\r\n$36\r\n9448dfc0-b041-4590-be50-452a66132f44\r\n$110\r\n*6\r\n$3\r\nSET\r\n$59\r\nl:b:k:sentry.grouptagvalue:df0c23da3fd89dd39342dfed00efd40d\r\n$1\r\n1\r\n$2\r\nEX\r\n$2\r\n10\r\n$2\r\nNX\r\n\r\n$1\r\n0\r\n$
7:S 05 Mar 2020 16:21:46.968 # == CRITICAL == This replica is sending an error to its master: 'EXEC without MULTI' after processing the command 'exec'
7:S 05 Mar 2020 16:21:46.968 #  querybuf: *1\r\n$4\r\nEXEC\r\n
7:S 05 Mar 2020 16:21:46.968 # == CRITICAL == This replica is sending an error to its master: 'Error in rreplay command, please check logs' after processing the command 'rreplay'
7:S 05 Mar 2020 16:21:46.968 #  querybuf: *5\r\n$7\r\nRREPLAY\r\n$36\r\n12f895d6-ed18-4acd-96fd-0f018402e3e0\r\n$15\r\n*1\r\n$5\r\nMULTI\r\n\r\n$1\r\n0\r\n$19\r\n1660341774621606332\r\n*5\r\n$7\r\nRREPLAY\r\n$36\r\n12f895d6-ed18-4acd-96fd-0f018402e3e0\r\n$101\r\n*4\r\n$4\r\nZADD\r\n$13\r\nunacked_index\r\n$17\r\n1583425306.965817\r\n$36\r\na270f227-aa34-46cd-805e-6cc462000058\r\n\r\n$1\r\n0\r\n$19\r\n1660341774621606333\r\n*5\r\n$7\r\nRREPLAY\r\n$36\r\n12f895d6-ed18-4acd-96fd-0f018402e3e0\r\n$10648\r\n*4\r\n$4\r\nHSET\r\n$7\r\nunacked\r\n$36\r\na270f227-aa34-46cd-805e-6cc462000058\r\n$10568\r\n[{"body": "gAJ9cQEoVQdleHBpcmVzcQJOVQN1dGNxA4hVBGFyZ3NxBF1xBVUFY2hvcmRxBk5VCWNhbGxiYWNrc3EHTlUIZXJyYmFja3NxCE5VB3Rhc2tzZXRxCU5VAmlkcQpVJGU3ZjJlODViLWI5NDItNGU2MC05ZmZjLWNmZmJhNmI5MTJmZnELVQdyZXRyaWVzcQxLAFUEdGFza3ENVSxzZW50cnkudGFza3MucG9zdF9wcm9jZXNzLnBvc3RfcHJvY2Vzc19ncm91cHEOVQl0aW1lbGltaXRxD05OhlUDZXRhcRBOVQZrd2FyZ3NxEX1xEihVGGlzX25ld19ncm91cF9lbnZpcm9ubWVudHETiVUGaXNfbmV3cRSJVQVldmVudHEVY2RqYW5nby5kYi5tb2RlbHMuYmFzZQptb2RlbF91bnBpY2tsZQpxFlUGc2
```

**Comment by JohnSully** [comment] 2020-03-06 02:06
Awesome that is super helpful!  I’ll get back to you in a bit.

**Comment by ekexcello** [comment] 2020-03-13 11:52
Hello.
Just got similar issue. We have a multimaster cluster of 3x KeyDB instances. After updating one node from 5.3.1 to 5.3.2 log on that node was flooded with error messages:
```
@400000005e6b6d1524a8162c 9854:S 13 Mar 2020 12:22:51.614 # == CRITICAL == This replica is sending an error to its master: 'Error in rreplay command, please check logs' after processing the command 'rreplay'
@400000005e6b6d1524a81a14 9854:S 13 Mar 2020 12:22:51.614 #     querybuf: *5\r\n$7\r\nRREPLAY\r\n$36\r\nc8326dfb-09b3-4dfa-84b0-d3dd998797f0\r\n$116\r\n*5\r\n$7\r\nRREPLAY\r\n$36\r\n710aaaf2-bf96-4293-b49c-c05a791d6953\r\n$15\r\n*1\r\n$5\r\nMULTI\r\n\r\n$2\r\n13\r\n$19\r\n1661047743783\r\n\r\n$2\r\n13\r\n$19\r\n1661047743729106983\r\n*5\r\n$7\r\nRREPLAY\r\n$36\r\nc8326dfb-09b3-4dfa-84b0-d3dd998797f0\r\n$220\r\n*5\r\n$7\r\nRREPLAY\r\n$36\r\n710aaaf2-bf96-4293-b49c-c05a791d6953\r\n$118\r\n*3\r\n$4\r\nSADD\r\n$24\r\nNette.Journal:10925:keys\r\n$66\r\nNette.Storage:collections.apiKeys:63ea0716ca***********ccb271e43161a5\r\n\r\n$2\r\n13\r\n$19\r\n1661047743783\r\n\r\n$2\r\n13\r\n$19\r\n1661047743729106985\r\n*5\r\n$7\r\nRREPLAY\r\n$36\r\nc8326dfb-09b3-4dfa-84b0-d3dd998797f0\r\n$219\r\n*5\r\n$7\r\nRREPLAY\r\n$36\r\n710aaaf2-bf96-4293-b49c-c05a791d6953\r\n$117\r\n*3\r\n$4\r\nSADD\r\n$85\r\nNette.Journal:Nette.Storage:collections.apiKeys:63ea0716ca***********ccb271e43161a5:tags\r\n$5\r\n10925\r\n\r\n$2\r\n13\r\n$19\r\n1661047743783\r\n\r\n$2\r\n13\r\n$19\r\n16610477
@400000005e6b6d1524a8450c 9854:S 13 Mar 2020 12:22:51.614 # == CRITICAL == This replica is sending an error to its master: 'Error in rreplay command, please check logs' after processing the command 'rreplay'
@400000005e6b6d1524a848f4 9854:S 13 Mar 2020 12:22:51.614 #     querybuf: *5\r\n$7\r\nRREPLAY\r\n$36\r\nc8326dfb-09b3-4dfa-84b0-d3dd998797f0\r\n$116\r\n*5\r\n$7\r\nRREPLAY\r\n$36\r\n710aaaf2-bf96-4293-b49c-c05a791d6953\r\n$15\r\n*1\r\n$5\r\nMULTI\r\n\r\n$2\r\n13\r\n$19\r\n1661047743783\r\n\r\n$2\r\n13\r\n$19\r\n1661047743729106983\r\n*5\r\n$7\r\nRREPLAY\r\n$36\r\nc8326dfb-09b3-4dfa-84b0-d3dd998797f0\r\n$220\r\n*5\r\n$7\r\nRREPLAY\r\n$36\r\n710aaaf2-bf96-4293-b49c-c05a791d6953\r\n$118\r\n*3\r\n$4\r\nSADD\r\n$24\r\nNette.Journal:10925:keys\r\n$66\r\nNette.Storage:collections.apiKeys:63ea0716ca***********ccb271e43161a5\r\n\r\n$2\r\n13\r\n$19\r\n1661047743783\r\n\r\n$2\r\n13\r\n$19\r\n1661047743729106985\r\n*5\r\n$7\r\nRREPLAY\r\n$36\r\nc8326dfb-09b3-4dfa-84b0-d3dd998797f0\r\n$219\r\n*5\r\n$7\r\nRREPLAY\r\n$36\r\n710aaaf2-bf96-4293-b49c-c05a791d6953\r\n$117\r\n*3\r\n$4\r\nSADD\r\n$85\r\nNette.Journal:Nette.Storage:collections.apiKeys:63ea0716ca***********ccb271e43161a5:tags\r\n$5\r\n10925\r\n\r\n$2\r\n13\r\n$19\r\n1661047743783\r\n\r\n$2\r\n13\r\n$19\r\n16610477
@400000005e6b6d1524a873ec 9854:S 13 Mar 2020 12:22:51.614 # == CRITICAL == This replica is sending an error to its master: 'Error in rreplay command, please check logs' after processing the command 'rreplay'
@400000005e6b6d1524a877d4 9854:S 13 Mar 2020 12:22:51.614 #     querybuf: *5\r\n$7\r\nRREPLAY\r\n$36\r\nc8326dfb-09b3-4dfa-84b0-d3dd998797f0\r\n$116\r\n*5\r\n$7\r\nRREPLAY\r\n$36\r\n710aaaf2-bf96-4293-b49c-c05a791d6953\r\n$15\r\n*1\r\n$5\r\nMULTI\r\n\r\n$2\r\n13\r\n$19\r\n1661047743783\r\n\r\n$2\r\n13\r\n$19\r\n1661047743729106983\r\n*5\r\n$7\r\nRREPLAY\r\n$36\r\nc8326dfb-09b3-4dfa-84b0-d3dd998797f0\r\n$220\r\n*5\r\n$7\r\nRREPLAY\r\n$36\r\n710aaaf2-bf96-4293-b49c-c05a791d6953\r\n$118\r\n*3\r\n$4\r\nSADD\r\n$24\r\nNette.Journal:10925:keys\r\n$66\r\nNette.Storage:collections.apiKeys:63ea0716ca***********ccb271e43161a5\r\n\r\n$2\r\n13\r\n$19\r\n1661047743783\r\n\r\n$2\r\n13\r\n$19\r\n1661047743729106985\r\n*5\r\n$7\r\nRREPLAY\r\n$36\r\nc8326dfb-09b3-4dfa-84b0-d3dd998797f0\r\n$219\r\n*5\r\n$7\r\nRREPLAY\r\n$36\r\n710aaaf2-bf96-4293-b49c-c05a791d6953\r\n$117\r\n*3\r\n$4\r\nSADD\r\n$85\r\nNette.Journal:Nette.Storage:collections.apiKeys:63ea0716ca***********ccb271e43161a5:tags\r\n$5\r\n10925\r\n\r\n$2\r\n13\r\n$19\r\n1661047743783\r\n\r\n$2\r\n13\r\n$19\r\n16610477
@400000005e6b6d1524a89714 9854:S 13 Mar 2020 12:22:51.614 # == CRITICAL == This replica is sending an error to its master: 'Error in rreplay command, please check logs' after processing the command 'rreplay'
@400000005e6b6d1524a89afc 9854:S 13 Mar 2020 12:22:51.614 #     querybuf: *5\r\n$7\r\nRREPLAY\r\n$36\r\nc8326dfb-09b3-4dfa-84b0-d3dd998797f0\r\n$991\r\n*5\r\n$7\r\nRREPLAY\r\n$36\r\n710aaaf2-bf96-4293-b49c-c05a791d6953\r\n$889\r\n*4\r\n$5\r\nSETEX\r\n$66\r\nNette.Storage:collections.apiKeys:63ea0716ca***********ccb271e43161a5\r\n$3\r\n600\r\n$784\r\n{"time":"0.60415300 1584098571","expire":1584099171,"serialized":true}
```
Attempt to upgrade second node rendered into same situation on two nodes.
An interesting option is that older version logged no issues and update of standalone instance also went well. However, we have had to roll back to 5.3.1 as it's not clear whether cluster of 5.3.2 will pick up dump of 5.3.1 and will be operational.

**Comment by JohnSully** [comment] 2020-03-25 21:37
The protocol error is here:
$19\r\n1661047743783\r\n\

That string is only 13 characters not 19.  Not yet sure how it is possible for us to write out the length incorrectly.

**Comment by JohnSully** [comment] 2020-03-25 22:55
@ekexcello are you on ARM?  Did you compile from source or use a per-packaged binary?

**Comment by JohnSully** [comment] 2020-03-26 01:58
I've got a repro and a fix.  Note @ekexcello your issue is slightly different than the earlier items in this bug but is also resolved in the same change.

In transactions we need to hold on to all queries since the MULTI.  The way we were storing this was incorrect when data was simultaneously relayed from multiple sources as can happen with multi master.

Fixed in change 6ec16412

**Comment by Antiarchitect** [comment] 2020-03-26 06:10
@JohnSully as soon as the 5.3.3 will be rolled out as eqalpha/keydb docker image I will create a new chart version with this fix

**Comment by JohnSully** [comment] 2020-03-26 06:21
@Antiarchitect I appreciate it!

**Comment by Antiarchitect** [comment] 2020-03-26 08:12
Here we go: https://hub.helm.sh/charts/enapter/keydb/0.7.1
I've updated keydb to 5.3.3 in two of my projects. At the moment - no replication errors. Thank you for this!

**Comment by ekexcello** [comment] 2020-03-26 09:38
> are you on ARM? Did you compile from source or use a pre-packaged binary, and for which OS/platform?

Just for information. We use Gentoo with kernel 4.19 on AMD-64, installed from source.

**Comment by Talkabout** [comment] 2020-03-26 09:54
Hi @JohnSully ,

I have now updated to 5.3.3 and unfortunately the "CRITICAL" error keeps on showing:

2020-03-26 10:52:23 | trafficserver.home | Warning (4) | KEYDB == CRITICAL == This replica is sending an error to its master: 'unknown command `5798273`, with args beginning with: ' after processing the command '<unknown>'
-- | -- | -- | --
  | 2020-03-26 10:52:14 | trafficserver.home | Warning (4) | KEYDB == CRITICAL == This replica is sending an error to its master: 'unknown command `5664514`, with args beginning with: ' after processing the command '<unknown>'
  | 2020-03-26 10:52:14 | monitorserver.home | Warning (4) | KEYDB == CRITICAL == This replica is sending an error to its master: 'unknown command `2364672`, with args beginning with: ' after processing the command '<unknown>'
  | 2020-03-26 10:52:04 | trafficserver.home | Warning (4) | KEYDB == CRITICAL == This replica is sending an error to its master: 'unknown command `333250`, with args beginning with: ' after processing the command '<unknown>'
  | 2020-03-26 10:52:04 | monitorserver.home | Warning (4) | KEYDB == CRITICAL == This replica is sending an error to its master: 'unknown command `422016`, with args beginning with: ' after processing the command '<unknown>'
  | 2020-03-26 10:52:03 | trafficserver.home | Warning (4) | KEYDB == CRITICAL == This replica is sending an error to its master: 'unknown command `7248769`, with args beginning with: ' after processing the command '<unknown>'
  | 2020-03-26 10:52:03 | trafficserver.home | Warning (4) | KEYDB == CRITICAL == This replica is sending an error to its master: 'unknown command `6484996`, with args beginning with: ' after processing the command '<unknown>'
  | 2020-03-26 10:52:03 | trafficserver.home | Warning (4) | KEYDB == CRITICAL == This replica is sending an error to its master: 'unknown command `6484994`, with args beginning with: ' after processing the command '<unknown>'
  | 2020-03-26 10:52:03 | monitorserver.home | Warning (4) | KEYDB == CRITICAL == This replica is sending an error to its master: 'unknown command `6716161`, with args beginning with: ' after processing the command '<unknown>'
  | 2020-03-26 10:51:57 | trafficserver.home | Warning (4) | KEYDB == CRITICAL == This replica is sending an error to its master: 'unknown command `2079875`, with args beginning with: ' after processing the command '<unknown>'
  | 2020-03-26 10:51:57 | trafficserver.home | Warning (4) | KEYDB == CRITICAL == This replica is sending an error to its master: 'unknown command `2079873`, with args beginning with: ' after processing the command '<unknown>'
  | 2020-03-26 10:51:54 | trafficserver.home | Warning (4) | KEYDB == CRITICAL == This replica is sending an error to its master: 'unknown command `5017858`, with args beginning with: ' after processing the command '<unknown>'
  | 2020-03-26 10:51:54 | monitorserver.home | Warning (4) | KEYDB == CRITICAL == This replica is sending an error to its master: 'unknown command `1155200`, with args beginning with: ' after processing the command '<unknown>'

Any suggestion?

Thanks!

Bye

**Comment by ekexcello** [comment] 2020-03-26 10:26
@JohnSully Can we kindly ask you to reopen this issue back as it seems to be still not fixed completely?

**Comment by Antiarchitect** [comment] 2020-03-26 11:18
My errors are gone completely in two applications I use KeyDB in.

**Comment by Talkabout** [comment] 2020-03-26 15:50
Unfortunately in my case even the keys got async in a master/master sync. Current values:


```
Redis version: | 5.3.3
-- | --
Keys: | 1746
Memory used: | 8.5 MB
Uptime: | 6 hours 16 mins 15 secs
Last save: | 12 secs ago
```
```
Redis version: | 5.3.3
-- | --
Keys: | 1742
Memory used: | 8.5 MB
Uptime: | 35 mins 19 secs
Last save: | 12 secs ago
```
I have not realized this problem before, but I might have not checked it. Fortunately my usage of the master/master concept is not that critical, but it would be good to solve it as other use cases might be more critical.

Bye

**Comment by JohnSully** [comment] 2020-03-26 17:16
Looks like there must be multiple issues here. At least we fixed some of them. 

For those who still experience the issue:
1) What is your network topology? Mulimaster? Are you using a mesh, a ring, some other setup? And how many nodes?

2) What OS are you using? Are you using the official docker images or compiling from source?

**Comment by Talkabout** [comment] 2020-03-26 17:22
Hi @JohnSully ,

I have a very simple topology:

server 1:

Raspberry Pi 4
Debian Buster
attached to netgear switch
ip: 192.168.20.10

server 2:

Raspberry Pi 4
Debian Buster
attached to netgear switch
ip: 192.168.20.2

I am compiling KeyDB from source on both the machines. The only additional configuration setting I have applied is:

active-replica yes
replicaof 192.168.20.2 6379

and vice versa.

I am using KeyDB as a "shared cache" for my 2 unbound resolvers. Both are storing their data in their KeyDB instance and through active replica I am making sure to not query same URLs again that were queried already on the other instance.

Hope that helps.

Bye

**Comment by JohnSully** [comment] 2020-03-26 17:29
Thanks @Talkabout. I only repro’d the issue with multimaster so it makes sense you don’t see it resolved. 

If you can run the monitor command on one of your hosts to give me an idea of what sort of commands its running that would be helpful. Alternatively if your resolver is open source i can try to duplicate your setup.

**Comment by Talkabout** [comment] 2020-03-26 17:39
@JohnSully 

I have attached the output of the monitor command for both the nodes separately, so you can compare what happened on both the nodes.

The resolver I am using is unbound, which is open source. To make it work with keydb (or redis) you need to compile from source, so it might be a little bit more effort. Tell me how I can help to debug the issue so there is no need for you to duplicate the setup.

Bye
[keydb_monitor_2.txt](https://github.com/JohnSully/KeyDB/files/4388862/keydb_monitor_2.txt)
[keydb_monitor_10.txt](https://github.com/JohnSully/KeyDB/files/4388863/keydb_monitor_10.txt)

**Comment by Talkabout** [comment] 2020-03-26 18:36
@JohnSully 

It is becoming even worse. The active replication seems to be completely broken. Any key that gets created on one of the instances is NOT synced to the other one. I am now reverting back to 5.3.1 and will check again. But I am pretty sure that with this version at least the replication was kind of stable.

**Comment by JohnSully** [comment] 2020-03-26 18:40
@Talkabout Before you revert if you could capture some of the network traffic between the two with tcpdump it would be helpful. 

There is definitely some corruption of the network protocol going on. Its clear from your monitor dump. I think it may be related to 32-bit ARM.

**Comment by JohnSully** [comment] 2020-03-26 18:40
Also if you run with only 1 server threads do the errors go away?

**Comment by Talkabout** [comment] 2020-03-26 18:54
I have attached the output of a tcpdump session with complete protocol decode (-v option). I hope it helps.

How to make the server run with only 1 thread?

Bye
[keydb_tcpdump_10.txt](https://github.com/JohnSully/KeyDB/files/4389305/keydb_tcpdump_10.txt)

**Comment by Talkabout** [comment] 2020-03-26 18:56
I have checked for "server-threads" variable but it is not used in my config file. The default value seems to be 1, so actually I am running both instances with 1 thread.

**Comment by Talkabout** [comment] 2020-03-26 19:08
as soon as I restart one of the nodes the synchronisation process works and both instances have the same keys. But keeping them run for a few minutes makes them having different amount of keys. It means some of the keys are synced, some are not. Weird behavior... Do you need anything else or can I go back to 5.3.1 now?

**Comment by JohnSully** [comment] 2020-03-26 19:11
Sorry it looks like tcpdump is putting it through a RESP parser so not giving the information I need since the RESP is corrupt. 

If you capture it in pcap format by using the -w <filename> argument it should save the raw bytes. Also ‘-s 65535’ to ensure it saves the whole packet and doesn’t truncate. 

If a replica fails to process commands from its master its not surprising it will be missing keys. The root cause is this bug. 

Once I get the pcap I think that’s all I need.

**Comment by Talkabout** [comment] 2020-03-26 19:18
Captured with this command:

sudo tcpdump -i eth0 -v -w keydb_tcpdump_pcap.txt -s 65535 port 6379

Is that fine?
[keydb_tcpdump_pcap.txt](https://github.com/JohnSully/KeyDB/files/4389457/keydb_tcpdump_pcap.txt)

**Comment by JohnSully** [comment] 2020-03-26 19:58
Thanks @Talkabout that's all I need.  I've got a few theories to work off of now.

**Comment by Talkabout** [comment] 2020-03-26 19:59
Good luck!

**Comment by Talkabout** [comment] 2020-03-26 20:22
Now back on 5.3.1, active replication works again. But as errors are still there, some keys might not get synced. But not as much as with 5.3.3.

Hoping for a fix, thanks again @JohnSully

**Comment by JohnSully** [comment] 2020-03-26 21:15
Dusted off my rPi and found the issue, we're not 32-bit clean.  But first how did you work around the build failures:
/usr/bin/ld: server.o: in function `pingCommand(client*)':
/usr/include/c++/8/bits/atomic_base.h:396: undefined reference to `__atomic_load_8'

**Comment by Talkabout** [comment] 2020-03-26 21:17
In my other post I have written that building on rPI was only possible by using this command line:

make LDFLAGS='-latomic'

with that the build process works.

**Comment by JohnSully** [comment] 2020-03-26 21:20
Thanks, just wanted to be sure we're testing the same things.  As part of this I'll ensure KeyDB builds cleanly on the rPi without extra flags.

```
replication.cpp:360:55: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 4 has type ‘uint64_t’ {aka ‘long long unsigned int’} [-Wformat=]
     int cchMvccNum = snprintf(szMvcc, sizeof(szMvcc), "%lu", mvccTstamp);
                                                       ^~~~~  ~~~~~~~~~~
replication.cpp:361:52: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 5 has type ‘uint64_t’ {aka ‘long long unsigned int’} [-Wformat=]
     int cchMvcc = snprintf(szMvcc, sizeof(szMvcc), "$%d\r\n%lu\r\n", cchMvccNum, mvccTstamp);
```

The following are the magic warnings indicating the bug.  However there are a bunch of other warnings that are concerning as well.  Nobody was using 32-bit on x86 but the rPi still needs it so I have to support it.

**Comment by Talkabout** [comment] 2020-03-26 21:22
I appreciate your help and your support!

**Comment by JohnSully** [comment] 2020-03-27 18:39
@Talkabout a fix has been pushed and the release tag for v5.3.3 has been updated.  You should also now be able to compile with just "make -j4" and not add any extra flags.

I've verified all tests are passing my rPi 3B

**Closed by JohnSully** 2020-03-27 18:39 UTC

**Comment by Talkabout** [comment] 2020-03-27 18:58
@JohnSully 

updated both nodes. No errors in log in the first few minutes, compilation process worked without issues. Replication works. Seems everything is good :)

Thanks you very much!

**Comment by JohnSully** [comment] 2020-03-27 19:28
For anyone tracking this bug the new fix is only needed if you are on 32-bit.
