### ISSUE TITLE
KeyDB 5.1.1 periodically crashes with assertion failed

### ISSUE THREAD

**Issue by sisoftrg** [JohnSully/KeyDB#107] opened 2019-11-19 06:46 UTC
I migrated from Redis few days ago, code from RELEASE_5. All work well except such crashes. My setup is active-active replication between 2 nodes, many write (non-overlaping) and read operations on both nodes.

Full log of last crash:
[bug.txt](https://github.com/JohnSully/KeyDB/files/3862291/bug.txt)

From dmesg:
```
[29821622.742679] keydb-server[3880]: segfault at ffffffffffffffff ip 000000000048dace sp 00007f78c4bfc0d0 error 7 in keydb-server[400000+1d0000]
[29854550.593999] keydb-server[27184]: segfault at 7f51602f ip 00007f4f602fbe08 sp 00007f4f602fbe10 error 6
[30118136.459673] traps: keydb-server[23276] general protection ip:4c0857 sp:7f22c91fc5a8 error:0 in keydb-server[400000+1d0000]
[30125101.951851] keydb-server[29442]: segfault at ffffffffffffffff ip 000000000048d488 sp 00007f43cf9fc4d0 error 7 in keydb-server[400000+1d0000]
[30132379.101028] keydb-server[31173]: segfault at ffffffffffffffff ip 000000000048d488 sp 00007f707f1fc4d0 error 7 in keydb-server[400000+1d0000]
[30218350.872854] keydb-server[19147]: segfault at ffffffffffffffff ip 000000000048d488 sp 00007f23fb63f4d0 error 7 in keydb-server[400000+1d0000]
```

Address of assertion:
```
$ addr2line -e /usr/local/bin/keydb-server 450963
/usr/src/KeyDB/src/networking.cpp:2152
```
```
    serverAssert(c->iel == ielFromEventLoop(el));
```

Please let me know if you need something more.

**Comment by JohnSully** [comment] 2019-11-20 21:16
Hi @sisoftrg 

In these cases KeyDB provides very good logs that allow me to diagnose the issue.  Can you go into the KeyDB logs (not the syslogs you sent here) and get me the crash message.  The most important information there is the full callstack - but it will tell you where to start copying.

**Comment by JohnSully** [comment] 2019-11-20 21:44
Also in the logs, are you seeing messages related to replication around when the crash happens?

**Comment by JohnSully** [comment] 2019-11-21 00:48
This is fixed in change: 8e4f3234

Docker unstable is rebuilt nightly, the new build will automatically resolve the corruption in your database.  This change will be in the next point release.

Note: There is now an incompatibility between old version active replicas and new ones.  It is permissible to connect them for the purposes of an active upgrade but two versions should not be run simultaneously for any other purpose.

Active replicas are now responsible for performing their own expirations - this means an older server will have stale keys kept around forever taking up memory (it will not show them to any clients).

**Comment by JohnSully** [comment] 2019-11-21 00:53
I mixed this up with a different bug.  This bug is still active.

**Comment by JohnSully** [comment] 2019-12-01 20:07
We're crashing because the client pointer is NULL.  All the codepaths that could lead here should be crashing much earlier so I'm still working on sorting out how this could happen.

Are you running any modules?

**Comment by JohnSully** [comment] 2019-12-01 23:20
Great news, I was able to repro this and get a fix.  The fix is in unstable and will be included in the next release.  unstable docker rebuilds nightly if you would like to try it.

The issue is caused if a new client connects around the time we finish an AOF rewrite.  A dangling fd for the AOF rewrite gets used for the new client resulting in the function being called with a NULL client pointer.

**Closed by JohnSully** 2019-12-01 23:20 UTC
