### ISSUE TITLE
Replica (active-active-active) DEL

### ISSUE THREAD

**Issue by mbfdias** [JohnSully/KeyDB#83] opened 2019-09-17 14:22 UTC
I start KeyDB 5.0.2 (71d5a106/0) 64 bit with persistence on nodes A:6379 B:6380 C:6381 using localhost for demo purposes using the most basic config

if I create a key with all nodes up and in sync, and delete the key while one node is down, the key magically reappears when I restart that node and it re-syncs.

Instance-A config file:

#assuming below parameters were set and IP address of this instance is 127.0.0.1
port 6379
requirepass mypassword123
masterauth mypassword123
multi-master yes
active-replica yes
replicaof 127.0.0.1 6380
replicaof 127.0.0.1 6381
dir ./A
dbfilename dump.rdb

Instance-B config file:

#assuming below parameters were set and IP address of this instance is 127.0.0.1
port 6380
requirepass mypassword123
masterauth mypassword123
multi-master yes
active-replica yes
replicaof 127.0.0.1 6379
replicaof 127.0.0.1 6381
dir ./B
dbfilename dump.rdb

Instance-C config file:

#assuming below parameters were set and IP address of this instance is 127.0.0.1
port 6381
requirepass mypassword123
masterauth mypassword123
multi-master yes
active-replica yes
replicaof 127.0.0.1 6380
replicaof 127.0.0.1 6379
dir ./C
dbfilename dump.rdb

#STEP 1 check if mycounter exists
for a in 6379 6380 6381; do redis-cli -a mypassword123 -p $a GET mycounter; done
(nil)
(nil)
(nil)

#STEP 2 increment mycounter
for a in 6379 6380 6381; do redis-cli -a mypassword123 -p $a INCR mycounter; done
(integer) 1
(integer) 2
(integer) 3

#STEP 3 get mycounter on all 3 nodes
for a in 6379 6380 6381; do redis-cli -a mypassword123 -p $a GET mycounter; done
"3"
"3"
"3"

#STEP 4 orderly shutdown node C so as to have it save the BD.
redis-cli -a mypassword123 -p 6381 shutdown

#STEP 5 check all nodes again C is down so connection refused is expected
for a in 6379 6380 6381; do redis-cli -a mypassword123 -p $a GET mycounter; done
"3"
"3"
Could not connect to Redis at 127.0.0.1:6381: Connection refused

#STEP 6 delete mycounter on node A 
redis-cli -a mypassword123 -p 6379 DEL mycounter
(integer) 1

#STEP 7 check if the DEL was replicated (node C is still down)
for a in 6379 6380 6381; do redis-cli -a mypassword123 -p $a GET mycounter; done
(nil)
(nil)
Could not connect to Redis at 127.0.0.1:6381: Connection refused

#STEP 8 restart the C node wait for it to sync

#STEP 9 check mycounter again... and voila mycounter reappears
for a in 6379 6380 6381; do redis-cli -a mypassword123 -p $a GET mycounter; done
"1"
"1"
"1"

since last operation wins, DEL was effectively the last operation, but it doesn't win

**Comment by yegors** [comment] 2019-09-26 16:19
@JohnSully Any feedback on this? Seems like a fairly critical issue for geo-distributed production deployments.

**Comment by bgort** [comment] 2019-09-26 18:10
This issue is of interest to me, as well.  I've been searching for a solution that allows me to scale Redis in (n) Master configuration without using clustering/sharding, sentinels, etc., for HA/geo-diversity, and KeyDB seems to fit, generally.  Hopefully whatever is causing this is an easy fix?  In the few days (time permitting) I should be able to test this here to confirm, if that's helpful?

**Comment by yegors** [comment] 2019-09-26 18:39
We're deploying a geo-distributed staging KeyDB cluster now for pre-production testing, so we can also assist if needed. This issue is a deal breaker for us as it stands.

**Comment by bgort** [comment] 2019-09-26 19:31
Testing myself now...

3x 5.0.2 nodes/servers on one host; configs are all substantially similar to:
```
port 2001 {2001..2003}
multi-master yes
active-replica yes
replicaof 127.0.0.1 2002
replicaof 127.0.0.1 2003
dir /usr/local/lib/keydb-a {a..c}
dbfilename dump.rdb
```

Startup went fine - no problems/errors, and the instances seemed to sync (according to their output) just fine.

Borrowing from @mbfdias:
```
# for i in {2001..2003}; do redis-cli -p $i GET cntr; done
(nil)
(nil)
(nil)
```

```
#  for i in {2001..2003}; do redis-cli -p $i INCR cntr; done
(integer) 1
(integer) 2
(integer) 3
```

```
# for i in {2001..2003}; do redis-cli -p $i GET cntr; done
"3"
"3"
"3"
```

```
# redis-cli -p 2001 shutdown
```
At this point, the other two nodes indicate the first one has failed in their output and they continuously try to reconnect/sync (the spam/flooding goes past the point of reasonable, imo - probably should just indicate that it's lost connection and is trying to reconnect, and then not continue to spam [every second] saying it can't).

```
# for i in {2001..2003}; do redis-cli -p $i GET cntr; done
Could not connect to Redis at 127.0.0.1:2001: Connection refused
"3"
"3"
```

```
# redis-cli -p 2002 DEL cntr
(integer) 1
```

```
# for i in {2001..2003}; do redis-cli -p $i GET cntr; done
Could not connect to Redis at 127.0.0.1:2001: Connection refused
(nil)
(nil)
```

Here we restart node a at port 2001...

```
-snip-
44066:S 26 Sep 2019 15:19:03.209 # Server initialized
44066:S 26 Sep 2019 15:19:03.209 * Loading RDB produced by version 5.0.2
44066:S 26 Sep 2019 15:19:03.209 * RDB age 751 seconds
44066:S 26 Sep 2019 15:19:03.209 * RDB memory usage when created 9.70 Mb
44066:S 26 Sep 2019 15:19:03.209 * DB loaded from disk: 0.000 seconds
44066:S 26 Sep 2019 15:19:03.209 * Before turning into a replica, using my master parameters to synthesize a cached
 master: I may be able to synchronize with the new master with just a partial transfer.
44066:S 26 Sep 2019 15:19:03.209 * Before turning into a replica, using my master parameters to synthesize a cached
 master: I may be able to synchronize with the new master with just a partial transfer.
44066:S 26 Sep 2019 15:19:03.209 * Ready to accept connections
44066:S 26 Sep 2019 15:19:03.209   Thread 0 alive.
44066:S 26 Sep 2019 15:19:03.209 * Connecting to MASTER 127.0.0.1:2002
44066:S 26 Sep 2019 15:19:03.209 * MASTER <-> REPLICA sync started
44066:S 26 Sep 2019 15:19:03.209 * Connecting to MASTER 127.0.0.1:2003
44066:S 26 Sep 2019 15:19:03.209 * MASTER <-> REPLICA sync started
44066:S 26 Sep 2019 15:19:03.210 * Non blocking connect for SYNC fired the event.
44066:S 26 Sep 2019 15:19:03.210 * Non blocking connect for SYNC fired the event.
44066:S 26 Sep 2019 15:19:03.210 * Master replied to PING, replication can continue...
44066:S 26 Sep 2019 15:19:03.210 * Master replied to PING, replication can continue...
44066:S 26 Sep 2019 15:19:03.210 * Partial resynchronization not possible (no cached master)
44066:S 26 Sep 2019 15:19:03.210 * Partial resynchronization not possible (no cached master)
44066:S 26 Sep 2019 15:19:03.211 * Full resync from master: c46653f9736419ce29c50a45b1414bc8e0df3969:26046
44066:S 26 Sep 2019 15:19:03.211 * Discarding previously cached master state.
44066:S 26 Sep 2019 15:19:03.211 * Full resync from master: c46653f9736419ce29c50a45b1414bc8e0df3969:26137
44066:S 26 Sep 2019 15:19:03.211 * Discarding previously cached master state.
44066:S 26 Sep 2019 15:19:08.215 # Opening the temp file needed for MASTER <-> REPLICA synchronization: File exists
44066:S 26 Sep 2019 15:19:08.215 * MASTER <-> REPLICA sync: receiving 176 bytes from master
44066:S 26 Sep 2019 15:19:08.216 * MASTER <-> REPLICA sync: Keeping old data
44066:S 26 Sep 2019 15:19:08.216 * MASTER <-> REPLICA sync: Loading DB in memory
44066:S 26 Sep 2019 15:19:08.216 * Loading RDB produced by version 5.0.2
44066:S 26 Sep 2019 15:19:08.216 * RDB age 5 seconds
44066:S 26 Sep 2019 15:19:08.216 * RDB memory usage when created 9.74 Mb
44066:S 26 Sep 2019 15:19:08.216 * MASTER <-> REPLICA sync: Finished with success
44066:S 26 Sep 2019 15:19:08.216 * Replica 127.0.0.1:2003 asks for synchronization
44066:S 26 Sep 2019 15:19:08.216 * Full resync requested by replica 127.0.0.1:2003
44066:S 26 Sep 2019 15:19:08.216 * Starting BGSAVE for SYNC with target: disk
44066:S 26 Sep 2019 15:19:08.217 * Background saving started by pid 44073
44066:S 26 Sep 2019 15:19:08.217 * Replica 127.0.0.1:2002 asks for synchronization
44066:S 26 Sep 2019 15:19:08.217 * Full resync requested by replica 127.0.0.1:2002
44066:S 26 Sep 2019 15:19:08.217 * Waiting for end of BGSAVE for SYNC
44073:C 26 Sep 2019 15:19:08.218 * DB saved on disk
44073:C 26 Sep 2019 15:19:08.218 * RDB: 0 MB of memory used by copy-on-write
44066:S 26 Sep 2019 15:19:08.316 * Background saving terminated with success
44066:S 26 Sep 2019 15:19:08.316 * Synchronization with replica 127.0.0.1:2003 succeeded
44066:S 26 Sep 2019 15:19:08.316 * Synchronization with replica 127.0.0.1:2002 succeeded
44066:S 26 Sep 2019 15:19:09.125 * Connecting to MASTER 127.0.0.1:2003
44066:S 26 Sep 2019 15:19:09.125 * MASTER <-> REPLICA sync started
44066:S 26 Sep 2019 15:19:09.125 * Non blocking connect for SYNC fired the event.
44066:S 26 Sep 2019 15:19:09.125 * Master replied to PING, replication can continue...
44066:S 26 Sep 2019 15:19:09.125 * Partial resynchronization not possible (no cached master)
44066:S 26 Sep 2019 15:19:09.126 * Full resync from master: c46653f9736419ce29c50a45b1414bc8e0df3969:26218
44066:S 26 Sep 2019 15:19:09.211 * MASTER <-> REPLICA sync: receiving 176 bytes from master
44066:S 26 Sep 2019 15:19:09.211 * MASTER <-> REPLICA sync: Keeping old data
44066:S 26 Sep 2019 15:19:09.211 * MASTER <-> REPLICA sync: Loading DB in memory
44066:S 26 Sep 2019 15:19:09.211 * Loading RDB produced by version 5.0.2
44066:S 26 Sep 2019 15:19:09.211 * RDB age 0 seconds
44066:S 26 Sep 2019 15:19:09.211 * RDB memory usage when created 9.82 Mb
44066:S 26 Sep 2019 15:19:09.211 * MASTER <-> REPLICA sync: Finished with success
```
and on b/2002 (c/2003 is substantially the same):
```
31919:S 26 Sep 2019 15:19:03.210 * Replica 127.0.0.1:2001 asks for synchronization
31919:S 26 Sep 2019 15:19:03.210 * Full resync requested by replica 127.0.0.1:2001
31919:S 26 Sep 2019 15:19:03.210 * Starting BGSAVE for SYNC with target: disk
31919:S 26 Sep 2019 15:19:03.211 * Background saving started by pid 44072
44072:C 26 Sep 2019 15:19:03.212 * DB saved on disk
44072:C 26 Sep 2019 15:19:03.212 * RDB: 0 MB of memory used by copy-on-write
31919:S 26 Sep 2019 15:19:03.250 * Background saving terminated with success
31919:S 26 Sep 2019 15:19:03.250 * Synchronization with replica 127.0.0.1:2001 succeeded
31919:S 26 Sep 2019 15:19:04.058 * Connecting to MASTER 127.0.0.1:2001
31919:S 26 Sep 2019 15:19:04.058 * MASTER <-> REPLICA sync started
31919:S 26 Sep 2019 15:19:04.058 * Non blocking connect for SYNC fired the event.
31919:S 26 Sep 2019 15:19:08.216 * Master replied to PING, replication can continue...
31919:S 26 Sep 2019 15:19:08.216 * Partial resynchronization not possible (no cached master)
31919:S 26 Sep 2019 15:19:08.217 * Full resync from master: c46653f9736419ce29c50a45b1414bc8e0df3969:26046
31919:S 26 Sep 2019 15:19:08.217 * Discarding previously cached master state.
31919:S 26 Sep 2019 15:19:08.316 * MASTER <-> REPLICA sync: receiving 176 bytes from master
31919:S 26 Sep 2019 15:19:08.317 * MASTER <-> REPLICA sync: Keeping old data
31919:S 26 Sep 2019 15:19:08.317 * MASTER <-> REPLICA sync: Loading DB in memory
31919:S 26 Sep 2019 15:19:08.317 * Loading RDB produced by version 5.0.2
31919:S 26 Sep 2019 15:19:08.317 * RDB age 0 seconds
31919:S 26 Sep 2019 15:19:08.317 * RDB memory usage when created 9.74 Mb
31919:S 26 Sep 2019 15:19:08.317 * MASTER <-> REPLICA sync: Finished with success
```

and it seems to have sync'd correctly...?
```
# for i in {2001..2003}; do redis-cli -p $i GET cntr; done
(nil)
(nil)
(nil)
```
Wondering what the differences might be, other than the auth/passwords.

What version are you using, @mbfdias ?  If 5.0.2, what do the logs on the restarted server look like?

**Comment by bgort** [comment] 2019-09-26 19:47
I just tried it with:
```
requirepass mypassword123
masterauth mypassword123
```
added to each of the configs, and I can now confirm what @mbfdias found, though my 'cntr' value is 3, instead of his 1.

everything is the same until here...
```
# redis-cli -p 2001 -a pwd123 --no-auth-warning shutdown
```
then
```
# for i in {2001..2003}; do redis-cli -p $i -a pwd123 --no-auth-warning GET cntr; done
Could not connect to Redis at 127.0.0.1:2001: Connection refused
"3"
"3"
```
then
```
# redis-cli -p 2002 -a pwd123 --no-auth-warning DEL cntr
(integer) 1
```
then
```
# for i in {2001..2003}; do redis-cli -p $i -a pwd123 --no-auth-warning GET cntr; done
Could not connect to Redis at 127.0.0.1:2001: Connection refused
(nil)
(nil)
```
then restarting node a/2001:
```
# keydb-server keydb-a.conf
44181:C 26 Sep 2019 15:39:40.635 * Notice: "active-replica yes" implies "replica-read-only no"
44181:C 26 Sep 2019 15:39:40.635 * Before turning into a replica, using my master parameters to synthesize a cached
 master: I may be able to synchronize with the new master with just a partial transfer.
44181:C 26 Sep 2019 15:39:40.635 # oO0OoO0OoO0Oo KeyDB is starting oO0OoO0OoO0Oo
44181:C 26 Sep 2019 15:39:40.635 # KeyDB version=5.0.2, bits=64, commit=00000000, modified=0, pid=44181, just started
44181:C 26 Sep 2019 15:39:40.635 # Configuration loaded
44181:S 26 Sep 2019 15:39:40.635 * Increased maximum number of open files to 10032 (it was originally set to 1024).
                                        KeyDB 5.0.2 (00000000/0) 64 bit
                                        Running in standalone mode
                                        Port: 2001
                                        PID: 44181
-snip-
44181:S 26 Sep 2019 15:39:40.636 # Server initialized
44181:S 26 Sep 2019 15:39:40.636 * Loading RDB produced by version 5.0.2
44181:S 26 Sep 2019 15:39:40.636 * RDB age 53 seconds
44181:S 26 Sep 2019 15:39:40.636 * RDB memory usage when created 9.72 Mb
44181:S 26 Sep 2019 15:39:40.636 * DB loaded from disk: 0.000 seconds
44181:S 26 Sep 2019 15:39:40.636 * Before turning into a replica, using my master parameters to synthesize a cached
 master: I may be able to synchronize with the new master with just a partial transfer.
44181:S 26 Sep 2019 15:39:40.636 * Before turning into a replica, using my master parameters to synthesize a cached
 master: I may be able to synchronize with the new master with just a partial transfer.
44181:S 26 Sep 2019 15:39:40.636 * Ready to accept connections
44181:S 26 Sep 2019 15:39:40.636   Thread 0 alive.
44181:S 26 Sep 2019 15:39:40.636 * Connecting to MASTER 127.0.0.1:2002
44181:S 26 Sep 2019 15:39:40.636 * MASTER <-> REPLICA sync started
44181:S 26 Sep 2019 15:39:40.636 * Connecting to MASTER 127.0.0.1:2003
44181:S 26 Sep 2019 15:39:40.636 * MASTER <-> REPLICA sync started
44181:S 26 Sep 2019 15:39:40.636 * Non blocking connect for SYNC fired the event.
44181:S 26 Sep 2019 15:39:40.636 * Non blocking connect for SYNC fired the event.
44181:S 26 Sep 2019 15:39:40.637 * Master replied to PING, replication can continue...
44181:S 26 Sep 2019 15:39:40.637 * Master replied to PING, replication can continue...
44181:S 26 Sep 2019 15:39:40.637 * Partial resynchronization not possible (no cached master)
44181:S 26 Sep 2019 15:39:40.637 * Partial resynchronization not possible (no cached master)
44181:S 26 Sep 2019 15:39:40.638 * Full resync from master: 0e84f3f71acd75cc93d20b98d82042e2b0e9c917:34351
44181:S 26 Sep 2019 15:39:40.638 * Discarding previously cached master state.
44181:S 26 Sep 2019 15:39:40.638 * Full resync from master: 0e84f3f71acd75cc93d20b98d82042e2b0e9c917:34284
44181:S 26 Sep 2019 15:39:40.638 * Discarding previously cached master state.
44181:S 26 Sep 2019 15:39:45.641 # Opening the temp file needed for MASTER <-> REPLICA synchronization: File exists
44181:S 26 Sep 2019 15:39:45.641 * MASTER <-> REPLICA sync: receiving 178 bytes from master
44181:S 26 Sep 2019 15:39:45.642 * MASTER <-> REPLICA sync: Keeping old data
44181:S 26 Sep 2019 15:39:45.642 * MASTER <-> REPLICA sync: Loading DB in memory
44181:S 26 Sep 2019 15:39:45.642 * Loading RDB produced by version 5.0.2
44181:S 26 Sep 2019 15:39:45.642 * RDB age 5 seconds
44181:S 26 Sep 2019 15:39:45.642 * RDB memory usage when created 9.76 Mb
44181:S 26 Sep 2019 15:39:45.642 * MASTER <-> REPLICA sync: Finished with success
44181:S 26 Sep 2019 15:39:45.643 * Replica 127.0.0.1:2003 asks for synchronization
44181:S 26 Sep 2019 15:39:45.643 * Full resync requested by replica 127.0.0.1:2003
44181:S 26 Sep 2019 15:39:45.643 * Starting BGSAVE for SYNC with target: disk
44181:S 26 Sep 2019 15:39:45.643 * Background saving started by pid 44188
44181:S 26 Sep 2019 15:39:45.643 * Replica 127.0.0.1:2002 asks for synchronization
44181:S 26 Sep 2019 15:39:45.643 * Full resync requested by replica 127.0.0.1:2002
44181:S 26 Sep 2019 15:39:45.643 * Waiting for end of BGSAVE for SYNC
44188:C 26 Sep 2019 15:39:45.645 * DB saved on disk
44188:C 26 Sep 2019 15:39:45.645 * RDB: 0 MB of memory used by copy-on-write
44181:S 26 Sep 2019 15:39:45.742 * Background saving terminated with success
44181:S 26 Sep 2019 15:39:45.742 * Synchronization with replica 127.0.0.1:2003 succeeded
44181:S 26 Sep 2019 15:39:45.742 * Synchronization with replica 127.0.0.1:2002 succeeded
44181:S 26 Sep 2019 15:39:46.551 * Connecting to MASTER 127.0.0.1:2002
44181:S 26 Sep 2019 15:39:46.551 * MASTER <-> REPLICA sync started
44181:S 26 Sep 2019 15:39:46.551 * Non blocking connect for SYNC fired the event.
44181:S 26 Sep 2019 15:39:46.551 * Master replied to PING, replication can continue...
44181:S 26 Sep 2019 15:39:46.552 * Partial resynchronization not possible (no cached master)
44181:S 26 Sep 2019 15:39:46.552 * Full resync from master: 0e84f3f71acd75cc93d20b98d82042e2b0e9c917:34523
44181:S 26 Sep 2019 15:39:46.617 * MASTER <-> REPLICA sync: receiving 224 bytes from master
44181:S 26 Sep 2019 15:39:46.618 * MASTER <-> REPLICA sync: Keeping old data
44181:S 26 Sep 2019 15:39:46.618 * MASTER <-> REPLICA sync: Loading DB in memory
44181:S 26 Sep 2019 15:39:46.618 * Loading RDB produced by version 5.0.2
44181:S 26 Sep 2019 15:39:46.618 * RDB age 0 seconds
44181:S 26 Sep 2019 15:39:46.618 * RDB memory usage when created 9.72 Mb
44181:S 26 Sep 2019 15:39:46.618 * MASTER <-> REPLICA sync: Finished with success
```
and on b/2002:
```
44122:S 26 Sep 2019 15:39:40.637 * Replica 127.0.0.1:2001 asks for synchronization
44122:S 26 Sep 2019 15:39:40.637 * Full resync requested by replica 127.0.0.1:2001
44122:S 26 Sep 2019 15:39:40.637 * Starting BGSAVE for SYNC with target: disk
44122:S 26 Sep 2019 15:39:40.637 * Background saving started by pid 44186
44186:C 26 Sep 2019 15:39:40.639 * DB saved on disk
44186:C 26 Sep 2019 15:39:40.639 * RDB: 0 MB of memory used by copy-on-write
44122:S 26 Sep 2019 15:39:40.654 * Background saving terminated with success
44122:S 26 Sep 2019 15:39:40.655 * Synchronization with replica 127.0.0.1:2001 succeeded
44122:S 26 Sep 2019 15:39:41.362 * Connecting to MASTER 127.0.0.1:2001
44122:S 26 Sep 2019 15:39:41.362 * MASTER <-> REPLICA sync started
44122:S 26 Sep 2019 15:39:41.362 * Non blocking connect for SYNC fired the event.
44122:S 26 Sep 2019 15:39:45.641 # Connection with replica client id #162 lost.
44122:S 26 Sep 2019 15:39:45.642 * Master replied to PING, replication can continue...
44122:S 26 Sep 2019 15:39:45.643 * Partial resynchronization not possible (no cached master)
44122:S 26 Sep 2019 15:39:45.643 * Full resync from master: 0e84f3f71acd75cc93d20b98d82042e2b0e9c917:34523
44122:S 26 Sep 2019 15:39:45.643 * Discarding previously cached master state.
44122:S 26 Sep 2019 15:39:45.742 * MASTER <-> REPLICA sync: receiving 206 bytes from master
44122:S 26 Sep 2019 15:39:45.743 * MASTER <-> REPLICA sync: Keeping old data
44122:S 26 Sep 2019 15:39:45.743 * MASTER <-> REPLICA sync: Loading DB in memory
44122:S 26 Sep 2019 15:39:45.743 * Loading RDB produced by version 5.0.2
44122:S 26 Sep 2019 15:39:45.743 * RDB age 0 seconds
44122:S 26 Sep 2019 15:39:45.743 * RDB memory usage when created 9.78 Mb
44122:S 26 Sep 2019 15:39:45.743 * MASTER <-> REPLICA sync: Finished with success
44122:S 26 Sep 2019 15:39:46.552 * Replica 127.0.0.1:2001 asks for synchronization
44122:S 26 Sep 2019 15:39:46.552 * Full resync requested by replica 127.0.0.1:2001
44122:S 26 Sep 2019 15:39:46.552 * Starting BGSAVE for SYNC with target: disk
44122:S 26 Sep 2019 15:39:46.552 * Background saving started by pid 44189
44189:C 26 Sep 2019 15:39:46.553 * DB saved on disk
44189:C 26 Sep 2019 15:39:46.554 * RDB: 0 MB of memory used by copy-on-write
44122:S 26 Sep 2019 15:39:46.617 * Background saving terminated with success
44122:S 26 Sep 2019 15:39:46.617 * Synchronization with replica 127.0.0.1:2001 succeeded
```
... then..
```
# for i in {2001..2003}; do redis-cli -p $i -a pwd123 --no-auth-warning GET cntr; done
"3"
"3"
"3"
```
... so this is related to the auths?

**Comment by bgort** [comment] 2019-09-26 20:11
To answer my own question:  no, it's not related to the auths.  I've tried this 4-5x now - with and without the auths - sometimes it does it, sometimes it doesn't.

Have even had this:
```
# for i in {2001..2003}; do redis-cli -p $i GET cntr; done
"6"
"6"
"6"
# redis-cli -p 2002 DEL cntr
(integer) 1
# for i in {2001..2003}; do redis-cli -p $i GET cntr; done
(nil)
(nil)
(nil)
# redis-cli -p 2001 shutdown
# for i in {2001..2003}; do redis-cli -p $i GET cntr; done
Could not connect to Redis at 127.0.0.1:2001: Connection refused
(nil)
(nil)
```
and restart/resync, and then:
```
[root@forma][752][~]# for i in {2001..2003}; do redis-cli -p $i GET cntr; done
"6"
"6"
"6"
```

**Comment by JohnSully** [comment] 2019-09-26 20:39
Sorry for the delay, I've been quite busy the last week.  I'm investigating this now.  More updates to follow.

**Comment by bgort** [comment] 2019-09-26 20:45
So far, I can see that this snippet from replication.cpp (starting at line 2124) has an issue:

```
   while(maxtries--) {
        snprintf(tmpfile,256,
            "temp-%d.%ld.rdb",(int)g_pserver->unixtime,(long int)getpid());
        dfd = open(tmpfile,O_CREAT|O_WRONLY|O_EXCL,0644);
        if (dfd != -1) break; 
        sleep(1);
    }
    if (dfd == -1) {
        serverLog(LL_WARNING,"Opening the temp file needed for MASTER <-> REPLICA synchronization: %s",strerror(errno));
        goto error;
    }
```

It's pausing for 5s on restart (maxretries * 1 sleep) and then complaining it couldn't open the temp file it needs.  Don't know much of anything about redis/keydb, or how any of this works, but that doesn't seem quite right, so trying to sort out what's going on there.

**Comment by JohnSully** [comment] 2019-09-26 20:51
@bgort 

For replication there are two modes: Disk and Diskless.  Disk is the default way Redis (and therefore KeyDB) perform replication, while diskless is newer.  

With disk based replication we save out an RDB file to a temporary file in the same way we'd save a backup dump.  Then we send that file over the network to the replica.  With disk based replication we perform streaming directly from KeyDB without an intermediate file.  The rationale from Redis to keep disk based the default was because it was better tested.

For disk based replication to work it has to be able to send the file, so that is a requirement.  Can you check that there is nothing obvious preventing the file from getting created? (e.g. running out of disk space, permissions, etc).

**Comment by bgort** [comment] 2019-09-26 20:59
Thanks for the explanation; I'd assumed it was transferring the data en masse into the temp file, but wasn't sure.

Anyway, removing O_EXCL lets it create its temp file; not sure why it's a problem, or why strerror() is reporting that the file already exists (see the error in the paste above).  I did verify that the filename is being generated reasonably, that the file doesn't already exist, and given that removing O_EXCL takes care of it it doesn't seem likely there's a permissions issue.  Seems like using O_EXCL would be best, either way.  Still digging.

Also, FYI, now seeing another error, though the sync seems to work, so far (3 tests):
```
# Failed trying to rename the temp DB into dump.rdb in MASTER <-> REPLICA synchroniz
ation: No such file or directory
```
Haven't looked for the issue here yet, but will do.

**Comment by JohnSully** [comment] 2019-09-26 21:02
If it works with removing O_EXCL then the issue is that there are already files with the same name in that directory.  Looking at the code there are a few flaws in how it attempts to both create and name these temporary files so it should be quite simple to fix this (assuming this is the only issue).

**Comment by bgort** [comment] 2019-09-26 21:11
It's actually opening (creating) the same file multiple times, looking at the output of strace, and the one causing the problem is failing... Trying to sort out what's going on.  Stand by.

**Comment by JohnSully** [comment] 2019-09-26 21:21
There is a bug with multi master where it attempts to directly move the temporary file it received into the database backup file.  This is a fine optimization if there's only one master, but really bad for multimaster.  

I would expect it to create the file for each master it is required to connect with.

**Comment by bgort** [comment] 2019-09-26 21:30
That explains it.

```
snprintf(tmpfile,256,"temp-%d.%d.%ld.rdb",(int)g_pserver->unixtime,rand(),(long int)getpid()); 
```

Seems to resolve the issue (so far, in my very limited testing).  Not sure if using rand() is 'approved', style-wise, but it seems reasonably safe to me.

**Comment by JohnSully** [comment] 2019-09-26 21:33
@bgort 

In an hour or so I'll have a patch which resolves this, I would appreciate it if you could give it a try as extra confirmation it resolves the problem.

Thanks for your help debugging!

**Comment by bgort** [comment] 2019-09-26 21:33
You're welcome.  And thanks for the quick response.  Just reply here when the patch is available so I'll be sure to see it.

**Comment by JohnSully** [comment] 2019-09-26 22:26
@bgort this issue you found is a more general issue than the one in the bug.  For DEL since the key no longer exists there is no timestamp to compare with so we will take the stale value.  The only solution is to track deletes if not all of our nodes are connected.

This is more than a quick fix so I'll update this bug when I've finished reworking the multi master replication logic.

**Comment by bgort** [comment] 2019-09-27 00:15
Let me know!

**Comment by JohnSully** [comment] 2019-09-27 00:37
@bgort Your issues are fixed in change e776474f6 which is now in unstable, when you get a chance it would be great if you can try it out.

I still need to fix the DEL issue which will be in a separate commit.  The fix is straightforward logically but will take a bit of time to complete and test.

**Comment by bgort** [comment] 2019-09-27 10:25
e776474 fixes the file-related issues/errors, but not the delete issue (as expected).

**Comment by JohnSully** [comment] 2019-09-27 17:19
There was one bug with my fix that caused us to leave stale rdb files around, this is fixed in change e1c962095.

@bgort your changes will make it into v5.1 however @mbfdias the DEL issue is postponed to v5.2.  The reason is it interacts with a large amount of refactoring I already have in my 5.2 branch so it needs to be released at the same time.

**Comment by bgort** [comment] 2019-09-29 08:27
@JohnSully Excellent.  Thank you very much.

I assume the DEL issue fix(es) will also cover expirations?  Many use redis for caching, and this often involves expiring data after a certain period of time.  And lists that have had items popped off and become empty?

**Comment by JohnSully** [comment] 2019-09-30 04:06
When I first implemented Active Replica I re-used the "writeable replica" code which I think is not the right way.  It's pretty simple to make this work - just have replicas run the expire code normally and only send DELs to non-active replicas.  It does require special logic for non-active replicas and older clients to make this work right.

So in v5.1 I'll put in the necessary compatibility so that it will be a seamless upgrade to v5.2 where this will be fixed.  It's a goal that we always have N-1 compatibility in terms of replication.

**Comment by JohnSully** [comment] 2019-11-21 04:36
@bgort The expire issue is fixed with bug #109.  Now each replica does its own expires and doesn't rely on receiving a DEL.

**Comment by JohnSully** [comment] 2019-11-22 01:06
This should now be fixed with change 3028a890.

The unstable docker image rebuilds nightly if you would like to try it.

**Closed by JohnSully** 2019-11-22 01:06 UTC
Labels: Target v5.2

**Comment by mbfdias** [comment] 2019-11-22 02:52
can confirm solved on the unstable branch.:-) did a quick compile and test run and was fine.

**Comment by bgort** [comment] 2019-11-25 16:48
Will give this a try soon. Thank you!
