### ISSUE TITLE
Enable multi-threading didn't improve the performance in cluster mode

### ISSUE THREAD

**Issue by hengku** [JohnSully/KeyDB#112] opened 2019-12-01 21:52 UTC
I tried a keydb cluster consisting of 4 multi-threaded keydb servers, but I didn't observe significant performance improvement comparing to a native redis cluster with 4 single-threaded redis servers running under the same environment. 

* Successfully complied keydb under Ubuntu 18.04

* All testing machines have 56 cores, 384GB RAM, and 10Gbps network 

* One machine running a keydb cluster having 4 keydb servers with "server-threads 8", "server-thread-affinity true", "maxmemory 100gb" of each

  I also tried 2, 4 threads with, without binding cores

* One machine running memtier-benchmark as the following: 

    memtier_benchmark -s <ip> -p <port> -d 128 -t 50 -c 1 --key-pattern=P:P -n 600000 --key-minimum=1 --key-maximum=30000000 --ratio 1:0 --hide-histogram

  I also tried 5, 10 threads with the payload of 1280, 640 bytes

* From the test cases above, I didn't observe significant performance improvement comparing to a native redis cluster with 4 single-threaded redis servers running under the same environment.

**Comment by JohnSully** [comment] 2019-12-01 23:17
Hi @hengku this is a dupe of #102.  I'm working on it!

**Closed by JohnSully** 2019-12-01 23:17 UTC

**Comment by JohnSully** [comment] 2020-02-11 06:07
@hengku change 1a4c322 has been added to address this.

This is really a "low load latency test" because with a cluster each individual node will only see 1/N requests.  We did not load balance clients across threads well in this low load situation leading to higher latency.  We now do a better job at grouping clients for reduced latency and higher throughput.

Note that if you add "-t 8" to your memtier command you will see signficantly higher performance because you are now stressing KeyDB past what one thread can provide.

**Comment by hengku** [comment] 2020-03-11 05:04
Thank you, John. I am trying the new code and will let you know the result. 

`_Note that if you add "-t 8" to your memtier command you will see signficantly higher performance because you are now stressing KeyDB past what one thread can provide._`

**I was using "-t 50" when I tested with memtier.**

**Comment by JohnSully** [comment] 2020-03-11 05:07
Yes you used -t 50 but you had reduced the clients per thread to 1. I would recommend using the default number of clients for testing high load scenarios. 

Still though low load latency is important and we should not ignore it.

**Comment by hengku** [comment] 2020-03-11 05:12
Sure, I will try as you suggested. Thanks again!

**Comment by JohnSully** [comment] 2020-03-11 05:37
Thanks. 

Also you can tune with the min-clients-per-thread setting. If you find my default is not optimal I’d love the feedback.
