### ISSUE TITLE
multi master network traffic

### ISSUE THREAD

**Issue by durzo** [JohnSully/KeyDB#205] opened 2020-06-20 16:56 UTC
I'm looking at running two KeyDB's in AWS as multi-master across availability zones but my initial testing shows a high amount of inter-master communication over the network (with 0 keys in the database).

Are there any plans to reduce this? I would typically expect to see only keepalive + replication data instead of a constant stream when both masters are idle.

**Comment by JohnSully** [comment] 2020-07-12 19:26
Hi @durzo yes, this is a major limitation of Multi Master at the moment and we do have plans to address it - although no concrete date is set.  The issue is caused by the fact we don't know the cluster topology and therefore we must relay messages to any connected nodes.  This greatly amplifies message traffic.

There are a few things you can do:
1) Use a ring topology instead of a mesh
2) I've added a new configuration option that will greatly help for mesh scenarios: multi-master-no-forward.  When this is set we don't forward messages from other masters.  This is somewhat dangerous as if you don't have a true mesh where every node is connected to every other nodes will miss messages.

multi-master-no-forward was just added today in change d99d06b1.  It will be in the next release.

**Comment by JohnSully** [comment] 2020-07-12 19:28
I'm closing this as we've added the new config which will cut network traffic significantly.  For a more complete fix we need to map the topology so we only send traffic to nodes we know need to see it.  This is a much bigger project.

Issue #63 tracks topology mapping.

**Closed by JohnSully** 2020-07-12 19:28 UTC

**Comment by durzo** [comment] 2020-07-12 20:05
Thank you @JohnSully for all you do
