### ISSUE TITLE
Active - Active RREPLAY fails when null bytes are in payload

### ISSUE THREAD

**Issue by agronick** [JohnSully/KeyDB#64] opened 2019-07-23 21:04 UTC
I have an active active setup. I previously configured two servers that worked without issue. With this new set of two servers I'm experiencing an issue with the replication. Certain SET commands are not persisted even though they are making their way to the opposite host.

Here you can see that a key named foo is set and nothing is done with it. When it gets a command to delete foo it executes it but it doesn't execute the set:
```
1563915692.847852 [0 10.18.28.156:6379] "RREPLAY" "c51dbe3b-6ed7-44fd-a2c1-3ea2dc443a2a" "*5\r\n$3\r\nSET\r\n$6\r\n:1:foo\r\n$18\r\n\x80\x04\x95\a\x00\x00\x00\x00\x00\x00\x00\x8c\x03bar\x94.\r\n$2\r\nPX\r\n$5\r\n30000\r\n"
^[[A1563915702.087488 [0 10.18.28.156:6379] "RREPLAY" "c51dbe3b-6ed7-44fd-a2c1-3ea2dc443a2a" "*1\r\n$4\r\nPING\r\n"
1563915702.087528 [0 ?:0] "PING"
1563915706.098791 [0 10.18.28.156:6379] "RREPLAY" "c51dbe3b-6ed7-44fd-a2c1-3ea2dc443a2a" "*2\r\n$3\r\nDEL\r\n$6\r\n:1:foo\r\n"
1563915706.098813 [0 ?:0] "DEL" ":1:foo"
```

Commands executed from the redis cli are saved as well
```
1563915792.952047 [0 10.18.28.156:6379] "RREPLAY" "c51dbe3b-6ed7-44fd-a2c1-3ea2dc443a2a" "*3\r\n$3\r\nset\r\n$3\r\nbar\r\n$1\r\n1\r\n"
1563915792.952121 [0 ?:0] "set" "bar" "1"
```

**Comment by JohnSully** [comment] 2019-07-23 22:43
Hi @agronick 

Is there anything unique with this setup vs your older one?  Especially with ACLs, AUTH, or command renaming?

Also, are the clocks on your two hosts synchronized?  This is used to ensure last write wins.

I will try to reproduce this.

**Comment by agronick** [comment] 2019-07-24 02:08
I don't think anything is different. I made them both with Ansible. These pair were made from cloning one of them. I thought they might have the same random seed since one was cloned but the uuids were different. KeyDb was installed after they were cloned. I did check the clocks and I will check again. They were within 10 seconds of eachother when I checked.

It seems that I had less luck with binary encoded data coming from Django. Setting simple numbers and strings on the cli worked more often.

I did try flushing, restarting, and deleting the database file. Sockets are used by app and the servers sync over ip. I will try some more tomorrow. Thanks for taking a look.

**Comment by agronick** [comment] 2019-07-24 16:41
Just wanted to leave a comment so you get the notification. I updated my previous comment. I think I'm getting close to figuring this out.

**Comment by JohnSully** [comment] 2019-07-24 16:52
The issue appears to be in how the RREPLAY is written for the data parameter:
$23\r\n\x80\x04\x95\x0c\x00\x00\x00\x00\x00\x00\x00}\x94\x8c\x01a\x94\x8c\x01b\x94s.

You can see there are only 20 bytes in the payload yet the length is set to 23.  This would explain why there's 3 bytes left in the querybuf after running the command, it got confused because it treated part of the RESP protocol as data due to the incorrect length.

Since you are handy with the debugger, it would be good if you can show me what the robj looks like on the machine that recieved the original query.  It's written out to an RREPLAY in replicationFeedSlave at the end.

**Comment by agronick** [comment] 2019-07-24 16:58
Sure thing. In the meantime I added this printf
```
        if (sdslen(c->querybuf)-c->qb_pos < (size_t)(c->bulklen+2)) {
            /* Not enough data (+2 == trailing \r\n) */
            printf("START||| querybuf: %s qb_pos: %i bulklen: %i\n |||END", c->querybuf, (int) c->qb_pos, (int) c->bulklen);
            break;
        } else {
```

Its producing output that looks like:
```
START||| querybuf: *5
$3
SET
$64
:1:django.contrib.sessions.cache1bshzu23o6xn4aedyrlu4ejo3eu910z2
$304
��% qb_pos: 90 bulklen: 304
 |||END
```

Might be useful.

**Comment by JohnSully** [comment] 2019-07-24 17:00
One more thing: can you run the monitor command on the master so I can see the original command that produced the data looked like.

**Comment by agronick** [comment] 2019-07-24 17:08
Here you go.

This is the master
```
1563988021.797563 [0 127.0.0.1:55646] "SET" ":1:django.contrib.sessions.cache2k0aik8tp8l79ljapw8cl4ubv7n47oq8" "\x80\x04\x95%\x01\x00\x00\x00\x00\x00\x00}\x94(\x8c\nlast_saved\x94GA\xd7N$\rs\x03\b\x8c\n_csrftoken\x94\x8c@zrmXG0qRPcntWlPdYUqTYfcU9A6fE4Lw1utH2YZ5bOyS511fLfDt4v1fJAsZKhli\x94\x8c\x1cuser_show_storeinfo_messages\x94\x88\x8c\r_auth_user_id\x94\x8c\x012\x94\x8c\x12_auth_user_backend\x94\x8c#login.auth_backend.MultiLdapBackend\x94\x8c\x0f_auth_user_hash\x94\x8c(5a3a65229df23555d3461a0204e44474c523768d\x94\x8c\nis_manager\x94\x88u." "PX" "10800000"
```

Here is the slave:
```
1563988021.798181 [0 10.18.28.156:6379] "RREPLAY" "f2c36824-db9e-49da-bc41-cfbcc35a1da0" "*5\r\n$3\r\nSET\r\n$64\r\n:1:django.contrib.sessions.cache2k0aik8tp8l79ljapw8cl4ubv7n47oq8\r\n$304\r\n\x80\x04\x95%\x01\x00\x00\x00\x00\x00\x00}\x94(\x8c\nlast_saved\x94GA\xd7N$\rs\x03\b\x8c\n_csrftoken\x94\x8c@zrmXG0qRPcntWlPdYUqTYfcU9A6fE4Lw1utH2YZ5bOyS511fLfDt4v1fJAsZKhli\x94\x8c\x1cuser_show_storeinfo_messages\x94\x88\x8c\r_auth_user_id\x94\x8c\x012\x94\x8c\x12_auth_user_backend\x94\x8c#login.auth_backend.MultiLdapBackend\x94\x8c\x0f_auth_user_hash\x94\x8c(5a3a65229df23555d3461a0204e44474c523768d\x94\x8c\nis_manager\x94\x88u.\r\n$2\r\nPX\r\n$8\r\n10800000\r\n"
1563988024.536283 [0 10.18.28.156:6379] "RREPLAY" "f2c36824-db9e-49da-bc41-cfbcc35a1da0" "*1\r\n$4\r\nPING\r\n"
1563988024.536329 [0 ?:0] "PING"
1563988034.566571 [0 10.18.28.156:6379] "RREPLAY" "f2c36824-db9e-49da-bc41-cfbcc35a1da0" "*1\r\n$4\r\nPING\r\n"
1563988034.566597 [0 ?:0] "PING"
```

I'm working on pulling that object out of the master.

**Comment by agronick** [comment] 2019-07-24 17:11
Here is that object. The argv in replicationFeedSlave. Let me know if this isn't what you were looking for,

```
(gdb) print *argv[0]
$6 = {type = 0, encoding = 8, lru = 3707064, refcount = {<std::__atomic_base<unsigned int>> = {static _S_alignment = 4, _M_i = 1}, <No data fields>}, mvcc_tstamp = 18446744073709551615, 
  m_ptr = 0x544553010303}
(gdb) print *argv[1]
$7 = {type = 0, encoding = 0, lru = 3707064, refcount = {<std::__atomic_base<unsigned int>> = {static _S_alignment = 4, _M_i = 1}, <No data fields>}, mvcc_tstamp = 1639960441332432897, 
  m_ptr = 0x7fffec4160a3}
(gdb) print *argv[2]
$8 = {type = 0, encoding = 0, lru = 3707064, refcount = {<std::__atomic_base<unsigned int>> = {static _S_alignment = 4, _M_i = 2}, <No data fields>}, mvcc_tstamp = 1639960441332432897, 
  m_ptr = 0x7fffec411b43}
(gdb) print *argv[3]
$9 = {type = 0, encoding = 8, lru = 3707064, refcount = {<std::__atomic_base<unsigned int>> = {static _S_alignment = 4, _M_i = 1}, <No data fields>}, mvcc_tstamp = 18446744073709551615, 
  m_ptr = 0x5850010202}
(gdb) print *argv[4]
$10 = {type = 0, encoding = 8, lru = 3707064, refcount = {<std::__atomic_base<unsigned int>> = {static _S_alignment = 4, _M_i = 1}, <No data fields>}, mvcc_tstamp = 18446744073709551615, 
  m_ptr = 0x3030383031010808}
(gdb) print *argv[5]
$11 = {type = 0, encoding = 8, lru = 3707064, refcount = {<std::__atomic_base<unsigned int>> = {static _S_alignment = 4, _M_i = 1}, <No data fields>}, mvcc_tstamp = 18446744073709551615, 
  m_ptr = 0x584e010202}
(gdb) print *argv[6]
Cannot access memory at address 0x0
```

**Comment by JohnSully** [comment] 2019-07-24 17:50
I can repro this issue.  I should have a fix out by tonight.

Thanks for all your help narrowing it down!

**Comment by agronick** [comment] 2019-07-24 19:03
Thank you. These replication features make my life a lot easier without having to worry about slaves turning into masters or masters turning into slaves.

**Comment by JohnSully** [comment] 2019-07-25 02:34
This is now fixed in both the unstable and RELEASE_5 branches.

The issue is actually much simpler, the RREPLAY messages are getting written correctly (I must have miscounted the characters).  The problem is your data has null bytes in it, and RREPLAY is accidentally not binary safe.

When copying the buffer over to the fake client for execution we use sdscat.  This function calls strlen() insternally which stops on the null byte in your data.  The correct way to copy it is with sdscatsds() which has the count separate and doesn't rely on the null terminator to get the length.

I've added a test to ensure this never happens again.

**Closed by JohnSully** 2019-07-25 02:34 UTC
Labels: Target v5.0, bug

**Comment by agronick** [comment] 2019-07-25 14:21
Awesome news.

**Comment by JohnSully** [comment] 2019-07-25 16:46
RELEASE_5. unstable has our new subexpire feature which hasn’t been shaken out yet.

**Comment by agronick** [comment] 2019-07-25 19:01
Cool. I tested the changes and confirmed that it fixed the issue.
