### ISSUE TITLE
Max memory problem

### ISSUE THREAD

**Issue by demianchuk** [JohnSully/KeyDB#230] opened 2020-08-24 08:36 UTC
Hi

I am having multi master keydb cluster consisting of 3 nodes
Here is keydb conf file:

port 7305
multi-master yes
bind 10.0.5.2 172.17.0.1
tcp-backlog 4096
timeout 0
tcp-keepalive 300
daemonize yes
supervised no
pidfile /var/run/keydb/keydb-server.pid
loglevel notice
logfile /var/log/keydb/keydb-server.log
stop-writes-on-bgsave-error yes
rdbcompression yes
rdbchecksum yes
dbfilename dump.rdb
dir /var/lib/keydb
replica-serve-stale-data yes
replica-read-only no
repl-diskless-sync no
repl-diskless-sync-delay 5
databases 16
repl-disable-tcp-nodelay no
lazyfree-lazy-eviction no
lazyfree-lazy-expire yes
lazyfree-lazy-server-del no
replica-lazy-flush yes
replica-priority 100
slave-serve-stale-data yes
slave-read-only no
repl-diskless-sync no
repl-diskless-sync-delay 15
repl-ping-slave-period 1
repl-disable-tcp-nodelay no
maxclients 60000
maxmemory 512m
maxmemory-policy allkeys-lru
appendonly no
appendfilename appendonly.aof
appendfsync everysec
no-appendfsync-on-rewrite no
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb
aof-load-truncated yes
lua-time-limit 5000
                    

After some time (1-3 weeks) my php application breaks and at logs I see next one message:
**OOM command not allowed when used memory > 'maxmemory'**

There is no errors at keydb server logs by itself, and keydb info does not show any problems also

From what I found here - https://ma.ttias.be/redis-oom-command-not-allowed-used-memory-maxmemory/
Seems keydb configuration is correct as I am using **maxmemory-policy allkeys-lru**

I found that problem at both versions 6.0.8 and 6.0.13, though still did not try 5.3.3
I assume that it is a bug
Do you have any ideas what it cab be causes by?

Another question - can you provide some clear instruction at documentation how to downgrade keydb properly?
I cant found it anywhere but would like to test 5.3.3 version - maybe that is the problem of 6th release only

Thanks

**Comment by mykhailosmolynets** [comment] 2020-08-25 12:13
It seems that you have already reached you **maxmemory** limit **512m** and keydb sends appropriate response - https://docs.keydb.dev/docs/memory-optimization/#memory-allocation. I had the same issue in 5.3.2, maxmemory policy didn't evict keys - https://github.com/JohnSully/KeyDB/issues/188. But it became ok in 6.0.8. What it keydb server memory usage? And check in `INFO stats` amount of evicted keys. Evicted keys should be greater than 0:
`expired_keys:31453912
expired_stale_perc:0.00
expired_time_cap_reached_count:0
evicted_keys:1214157`

**Comment by demianchuk** [comment] 2020-08-25 13:01
Yes, I reached memory limit at 512m - I remember that I saw that while checking info | grep used_memory_human
But I did not check evicted_keys. Simply had to reload keydb to make dev environment working. But suppose that problem  was connected with fact that keydb could not delete evicted keys

Current statistics looks like:
total_connections_received:17906114
total_commands_processed:154974966
instantaneous_ops_per_sec:207
total_net_input_bytes:17246419673
total_net_output_bytes:8055323855252
instantaneous_input_kbps:20.28
instantaneous_output_kbps:9175.88
rejected_connections:0
sync_full:1
sync_partial_ok:0
sync_partial_err:0
expired_keys:3114548
expired_stale_perc:0.00
expired_time_cap_reached_count:0
expire_cycle_cpu_milliseconds:0
evicted_keys:347080
keyspace_hits:43818072
keyspace_misses:12289694
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:3720
migrate_cached_sockets:0
slave_expires_tracked_keys:2503786
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0
tracking_total_keys:0
tracking_total_items:0
tracking_total_prefixes:0
unexpected_error_replies:0

So seems evicted_keys are removed but maybe there is some case when it is not happens properly
Question is when and why it happens?

**Comment by demianchuk** [comment] 2020-08-27 22:01
Hi

I got maxmemory problem again

Here is info stats
total_connections_received:11853097
total_commands_processed:93962402
instantaneous_ops_per_sec:25
total_net_input_bytes:10286052532
total_net_output_bytes:3521467258019
instantaneous_input_kbps:7.62
instantaneous_output_kbps:6.03
rejected_connections:0
sync_full:2
sync_partial_ok:0
sync_partial_err:0
expired_keys:1987135
expired_stale_perc:0.00
expired_time_cap_reached_count:0
expire_cycle_cpu_milliseconds:0
evicted_keys:350145
keyspace_hits:22594094
keyspace_misses:8249429
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:4128
migrate_cached_sockets:0
slave_expires_tracked_keys:4637188
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0
tracking_total_keys:0
tracking_total_items:0
tracking_total_prefixes:0
unexpected_error_replies:0

And here is all info

# Server
redis_version:6.0.13
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:5055ac929b8ff5fb
redis_mode:standalone
os:Linux 4.15.0-108-generic x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:7.3.0
process_id:24065
run_id:97d1e351d7921e4ea48947acb61dba1a78ffe9a0
tcp_port:7305
uptime_in_seconds:868411
uptime_in_days:10
hz:10
configured_hz:10
lru_clock:4730073
executable:/usr/bin/keydb-server
config_file:/etc/keydb/keydb.conf

# Clients
connected_clients:6
client_recent_max_input_buffer:2
client_recent_max_output_buffer:0
blocked_clients:0
tracking_clients:0
clients_in_timeout_table:0
current_client_thread:0
thread_0_clients:7

# Memory
used_memory:512043344
used_memory_human:488.32M
used_memory_rss:507600896
used_memory_rss_human:484.09M
used_memory_peak:512908776
used_memory_peak_human:489.15M
used_memory_peak_perc:99.83%
used_memory_overhead:56114596
used_memory_startup:54962688
used_memory_dataset:455928748
used_memory_dataset_perc:99.75%
allocator_allocated:512633320
allocator_active:513708032
allocator_resident:531030016
total_system_memory:16422928384
total_system_memory_human:15.30G
used_memory_lua:34816
used_memory_lua_human:34.00K
used_memory_scripts:216
used_memory_scripts_human:216B
number_of_cached_scripts:1
maxmemory:512000000
maxmemory_human:488.28M
maxmemory_policy:allkeys-lru
allocator_frag_ratio:1.00
allocator_frag_bytes:1074712
allocator_rss_ratio:1.03
allocator_rss_bytes:17321984
rss_overhead_ratio:0.96
rss_overhead_bytes:-23429120
mem_fragmentation_ratio:0.99
mem_fragmentation_bytes:-4378968
mem_not_counted_for_evict:0
mem_replication_backlog:1048576
mem_clients_slaves:17186
mem_clients_normal:85930
mem_aof_buffer:0
mem_allocator:jemalloc-5.1.0
active_defrag_running:0
lazyfree_pending_objects:0

# Persistence
loading:0
rdb_changes_since_last_save:8439572
rdb_bgsave_in_progress:0
rdb_last_save_time:1597697250
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:0
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:1150976
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0
module_fork_in_progress:0
module_fork_last_cow_size:0

# Stats
total_connections_received:11854135
total_commands_processed:93964997
instantaneous_ops_per_sec:37
total_net_input_bytes:10287290809
total_net_output_bytes:3521467409852
instantaneous_input_kbps:22.72
instantaneous_output_kbps:1.03
rejected_connections:0
sync_full:2
sync_partial_ok:0
sync_partial_err:0
expired_keys:1987135
expired_stale_perc:0.00
expired_time_cap_reached_count:0
expire_cycle_cpu_milliseconds:0
evicted_keys:350145
keyspace_hits:22594094
keyspace_misses:8250895
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:4128
migrate_cached_sockets:0
slave_expires_tracked_keys:4637188
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0
tracking_total_keys:0
tracking_total_items:0
tracking_total_prefixes:0
unexpected_error_replies:0

# Replication
role:active-replica
master_global_link_status:up
Master 0: 
master_host:10.0.5.4
master_port:7305
master_link_status:up
master_last_io_seconds_ago:1
master_sync_in_progress:0
slave_repl_offset:24126113621
Master 1: 
master_host:10.0.5.3
master_port:7305
master_link_status:up
master_last_io_seconds_ago:1
master_sync_in_progress:0
slave_repl_offset:9535164943
slave_priority:100
slave_read_only:0
connected_slaves:1
slave0:ip=10.0.5.3,port=7305,state=online,offset=6646284277,lag=1
master_replid:7786edd855217522d65e7165f2927cd7b01278a3
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:6646284606
second_repl_offset:-1
repl_backlog_active:1
repl_backlog_size:1048576
repl_backlog_first_byte_offset:6645236031
repl_backlog_histlen:1048576

# CPU
used_cpu_sys:7946.906946
used_cpu_user:7241.161493
used_cpu_sys_children:0.008193
used_cpu_user_children:0.094001
server_threads:1
long_lock_waits:0

# Modules

# Cluster
cluster_enabled:0

I am still applying with help at that case

**Comment by JohnSully** [comment] 2020-09-22 21:44
Hi @demianchuk I think this is a dupe of #234 as you are also using Active Replication and expires.  Despite your bug coming in first there was a hint in 234 that lead to the solution.

**Closed by JohnSully** 2020-09-22 21:44 UTC
