### ISSUE TITLE
Replica (active-active)

### ISSUE THREAD

**Issue by rickytato** [JohnSully/KeyDB#81] opened 2019-09-14 14:47 UTC
I'm testing replication active-active (but the problem exists also in master/slave replication)... not work :)

My goal is: master-master node, with storage on SSD (maybe NVMe) on BTRFS, with HAProxy in front.
I compiled release 5.0.2 with ```make MALLOC=memkind``` on Debian 10 with BTRFS data partition mounted in ```/data```

With simple test, by shell, I can write data on every node (two node in totale, master-master) and work without any problem; but when I test mass insertion on LIST with PHP after some minutes slave crash.

In the **MASTER** node (the node I write in by PHP):
```
17534:C 13 Sep 2019 20:12:59.952 # oO0OoO0OoO0Oo KeyDB is starting oO0OoO0OoO0Oo
17534:C 13 Sep 2019 20:12:59.952 # KeyDB version=5.0.2, bits=64, commit=00000000, modified=0, pid=17534, just started
17534:C 13 Sep 2019 20:12:59.952 # Configuration loaded
17535:M 13 Sep 2019 20:12:59.962 # Server initialized
17535:M 13 Sep 2019 20:16:25.966   Thread 0 alive.
17535:M 13 Sep 2019 20:16:25.966   Thread 1 alive.
17535:M 13 Sep 2019 20:23:59.122 # Error registering fd event for the new client: No such file or directory (fd=94)
17535:M 13 Sep 2019 20:23:59.123 # Error registering fd event for the new client: No such file or directory (fd=94)
17535:M 13 Sep 2019 20:23:59.123 # Error registering fd event for the new client: No such file or directory (fd=94)
17535:M 13 Sep 2019 20:23:59.123 # Error registering fd event for the new client: No such file or directory (fd=94)
17535:M 13 Sep 2019 20:23:59.123 # Error registering fd event for the new client: No such file or directory (fd=94)
```

In the **SLAVE** log I've many message such as:
```
15947:S 13 Sep 2019 22:42:13.669 * Connecting to MASTER 192.168.x.y:16379
15947:S 13 Sep 2019 22:42:13.669 * MASTER <-> REPLICA sync started
15947:S 13 Sep 2019 22:42:13.669 # Error condition on socket for SYNC: Connection refused
15947:S 13 Sep 2019 22:42:14.104 - Accepted 192.168.x.y:63656
15947:S 13 Sep 2019 22:42:14.105 - Reading from client: Connection reset by peer
15947:S 13 Sep 2019 22:42:14.257 - Accepted 192.168.x.z:6212
15947:S 13 Sep 2019 22:42:14.257 - Reading from client: Connection reset by peer
15947:S 13 Sep 2019 22:42:14.671 * Connecting to MASTER 192.168.z.y:16379
15947:S 13 Sep 2019 22:42:14.671 * MASTER <-> REPLICA sync started
15947:S 13 Sep 2019 22:42:14.671 # Error condition on socket for SYNC: Connection refused
```
PHP quit with message:
```
Fatal error: Uncaught Predis\Response\ServerException: LOADING Redis is loading the dataset in memory 
```

In the config I've (this config without replication works great!):
```
tcp-backlog 65535
tcp-keepalive 30

save 900 1
save 300 100

dir /data/16379
dbfilename dump.rdb
appendonly yes
appendfsync no

lazyfree-lazy-eviction no
lazyfree-lazy-expire no
lazyfree-lazy-server-del no
replica-lazy-flush no
repl-backlog-size 16mb
repl-timeout 600

hash-max-ziplist-entries 512
hash-max-ziplist-value 64
list-max-ziplist-size -2
list-compress-depth 0
set-max-intset-entries 512
zset-max-ziplist-entries 128
zset-max-ziplist-value 64
hll-sparse-max-bytes 3000
stream-node-max-bytes 4096
stream-node-max-entries 100
client-output-buffer-limit normal 0 0 0
client-output-buffer-limit replica 0 0 0
client-output-buffer-limit pubsub 0 0 0

hz 10
dynamic-hz yes

aof-rewrite-incremental-fsync yes
rdb-save-incremental-fsync yes

replicaof 192.168.x.y 16379
replica-serve-stale-data yes
replica-read-only no
scratch-file-path /data/16379
server-threads 2
active-replica yes
```

**Comment by JohnSully** [comment] 2019-09-19 20:48
Hi Ricky,

I was thrown off a bit by you mentioning a crash.  If the only errors you see are "Error registering fd event for the new client" then I believe you are seeing the same issue as #82 - in which case I have a fix committed to unstable.

However if you see this in the logs:
> === KEYDB BUG REPORT START: Cut & paste starting from here ===
Then it is indeed a crash and would need more investigation.

**Comment by JohnSully** [comment] 2019-09-27 17:20
Dupe of #82.

**Closed by JohnSully** 2019-09-27 17:20 UTC
