### ISSUE TITLE
Corrupt subexpire entry in RDB skipping

### ISSUE THREAD

**Issue by rplant8** [JohnSully/KeyDB#154] opened 2020-03-19 09:53 UTC
Keydb started restarting(crashing?) about once a day after using expiremember for hash set. After restart all ttl are lost. When manually restarted, the behavior is the same. Ubuntu 16.04, KeyDB version = 5.3.2, bits = 64, commit = e523afa7. On 5.3.1 it was also, switched to 5.3.2.
3 bases, size 7-180MB. expiremember is set for a day and a month.
** Log Files **
20695:M 16 Mar 2020 19:02:07.036 * Background saving started by pid 2114
2114:C 16 Mar 2020 19:02:07.344 * DB saved on disk
2114:C 16 Mar 2020 19:02:07.349 * RDB: 1 MB of memory used by copy-on-write
20695:M 16 Mar 2020 19:02:07.439 * Background saving terminated with success
2125:C 16 Mar 2020 19:02:15.670 # oO0OoO0OoO0Oo KeyDB is starting oO0OoO0OoO0Oo
2125:C 16 Mar 2020 19:02:15.670 # KeyDB version=5.3.2, bits=64, commit=e523afa7, modified=0, pid=2125, just started
2125:C 16 Mar 2020 19:02:15.670 # Configuration loaded
2128:M 16 Mar 2020 19:02:15.697 * Running mode=standalone, port=6375.
2128:M 16 Mar 2020 19:02:15.697 # Server initialized
2128:M 16 Mar 2020 19:02:15.697 * Loading RDB produced by version 5.3.2
2128:M 16 Mar 2020 19:02:15.697 * RDB age 8 seconds
2128:M 16 Mar 2020 19:02:15.697 * RDB memory usage when created 35.73 Mb
2128:M 16 Mar 2020 19:02:15.699 # Corrupt subexpire entry in RDB skipping.
2128:M 16 Mar 2020 19:02:15.700 # Corrupt subexpire entry in RDB skipping.
... many-many ...
2128:M 16 Mar 2020 19:02:16.077 # Corrupt subexpire entry in RDB skipping.
2128:M 16 Mar 2020 19:02:16.077 # Corrupt subexpire entry in RDB.
2128:M 16 Mar 2020 19:02:16.077 * DB loaded from disk: 0.380 seconds
2128:M 16 Mar 2020 19:02:16.077 * Ready to accept connections
2128:M 16 Mar 2020 19:02:16.077   Thread 0 alive.
2128:M 16 Mar 2020 19:02:16.529 * Replica 10.254.10.2:16375 asks for synchronization
2128:M 16 Mar 2020 19:02:16.529 * Partial resynchronization not accepted: Replication ID mismatch (Replica asked for 'a30776c95116669d03eac1fc42411d182d48547f', my replication IDs are 'c232f440f67d6a80175b731079980c05685de070' and '0000000000000000000000000000000000000000')
2128:M 16 Mar 2020 19:02:16.529 * Starting BGSAVE for SYNC with target: disk
2128:M 16 Mar 2020 19:02:16.531 * Background saving started by pid 2133
2128:M 16 Mar 2020 19:02:16.725 * Replica 10.254.10.1:16375 asks for synchronization
2128:M 16 Mar 2020 19:02:16.725 * Partial resynchronization not accepted: Replication ID mismatch (Replica asked for 'a30776c95116669d03eac1fc42411d182d48547f', my replication IDs are 'ebf12647a855a42b1c756f71c45c5e30156be5f4' and '0000000000000000000000000000000000000000')
2128:M 16 Mar 2020 19:02:16.726 * Waiting for end of BGSAVE for SYNC
2133:C 16 Mar 2020 19:02:16.771 * DB saved on disk
2133:C 16 Mar 2020 19:02:16.774 * RDB: 1 MB of memory used by copy-on-write
2128:M 16 Mar 2020 19:02:16.799 * Background saving terminated with success
2128:M 16 Mar 2020 19:02:17.057 * Replica 172.21.10.1:16375 asks for synchronization
2128:M 16 Mar 2020 19:02:17.057 * Partial resynchronization not accepted: Replication ID mismatch (Replica asked for 'a30776c95116669d03eac1fc42411d182d48547f', my replication IDs are 'ebf12647a855a42b1c756f71c45c5e30156be5f4' and '0000000000000000000000000000000000000000')
2128:M 16 Mar 2020 19:02:17.057 * Starting BGSAVE for SYNC with target: disk
2128:M 16 Mar 2020 19:02:17.059 * Background saving started by pid 2134
2128:M 16 Mar 2020 19:02:17.128 * Synchronization with replica 10.254.10.1:16375 succeeded
2134:C 16 Mar 2020 19:02:17.263 * DB saved on disk
2134:C 16 Mar 2020 19:02:17.266 * RDB: 0 MB of memory used by copy-on-write
2128:M 16 Mar 2020 19:02:17.300 * Background saving terminated with success
2128:M 16 Mar 2020 19:02:27.029 * Synchronization with replica 10.254.10.2:16375 succeeded
2128:M 16 Mar 2020 19:02:30.077 * Synchronization with replica 172.21.10.1:16375 succeeded
2128:M 16 Mar 2020 19:04:58.049 * 10000 changes in 160 seconds. Saving...
2128:M 16 Mar 2020 19:04:58.056 * Background saving started by pid 2143
2143:C 16 Mar 2020 19:04:58.302 * DB saved on disk

22489:C 04 Mar 2020 17:43:37.633 # oO0OoO0OoO0Oo KeyDB is starting oO0OoO0OoO0Oo  < migration to keydb
8071:C 12 Mar 2020 18:12:40.270 # oO0OoO0OoO0Oo KeyDB is starting oO0OoO0OoO0Oo  < start using expiremember
14314:C 13 Mar 2020 18:14:18.677 # oO0OoO0OoO0Oo KeyDB is starting oO0OoO0OoO0Oo
20243:C 14 Mar 2020 16:56:12.677 # oO0OoO0OoO0Oo KeyDB is starting oO0OoO0OoO0Oo
27201:C 15 Mar 2020 16:57:04.422 # oO0OoO0OoO0Oo KeyDB is starting oO0OoO0OoO0Oo
1578:C 16 Mar 2020 17:00:38.417 # oO0OoO0OoO0Oo KeyDB is starting oO0OoO0OoO0Oo
8391:C 17 Mar 2020 17:02:32.167 # oO0OoO0OoO0Oo KeyDB is starting oO0OoO0OoO0Oo
22754:C 18 Mar 2020 17:12:11.168 # oO0OoO0OoO0Oo KeyDB is starting oO0OoO0OoO0Oo

127.0.0.1:6378> info
# Server
redis_version:5.3.2
redis_git_sha1:e523afa7
redis_git_dirty:0
redis_build_id:60d1a724ba236b03
redis_mode:standalone
os:Linux 4.4.0-164-generic x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:5.4.0
process_id:22757
run_id:58f88069d8198d830f6a25610de3dd20076483d1
tcp_port:6378
uptime_in_seconds:58487
uptime_in_days:0
hz:10
configured_hz:10
lru_clock:7551714
executable:/usr/bin/redis-server
config_file:/etc/redis/redis2.conf

# Clients
connected_clients:407
client_recent_max_input_buffer:2
client_recent_max_output_buffer:8406640
blocked_clients:0
current_client_thread:0
thread_0_clients:410

# Memory
used_memory:368030024
used_memory_human:350.98M
used_memory_rss:377028608
used_memory_rss_human:359.56M
used_memory_peak:380918168
used_memory_peak_human:363.27M
used_memory_peak_perc:96.62%
used_memory_overhead:19218124
used_memory_startup:9064984
used_memory_dataset:348811900
used_memory_dataset_perc:97.17%
allocator_allocated:368136696
allocator_active:373805056
allocator_resident:390647808
total_system_memory:2046820352
total_system_memory_human:1.91G
used_memory_lua:37888
used_memory_lua_human:37.00K
used_memory_scripts:0
used_memory_scripts_human:0B
number_of_cached_scripts:0
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
allocator_frag_ratio:1.02
allocator_frag_bytes:5668360
allocator_rss_ratio:1.05
allocator_rss_bytes:16842752
rss_overhead_ratio:0.97
rss_overhead_bytes:-13619200
mem_fragmentation_ratio:1.02
mem_fragmentation_bytes:9040584
mem_not_counted_for_evict:0
mem_replication_backlog:1048576
mem_clients_slaves:84162
mem_clients_normal:7922298
mem_aof_buffer:0
mem_allocator:jemalloc-5.1.0
active_defrag_running:0
lazyfree_pending_objects:0

# Persistence
loading:0
rdb_changes_since_last_save:69461
rdb_bgsave_in_progress:0
rdb_last_save_time:1584609936
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:3
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:10067968
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0

# Stats
total_connections_received:13435
total_commands_processed:52290552
instantaneous_ops_per_sec:936
total_net_input_bytes:4451544823
total_net_output_bytes:13698419814
instantaneous_input_kbps:78.92
instantaneous_output_kbps:218.51
rejected_connections:0
sync_full:4
sync_partial_ok:0
sync_partial_err:4
expired_keys:9087
expired_stale_perc:0.00
expired_time_cap_reached_count:0
evicted_keys:0
keyspace_hits:445339
keyspace_misses:420846
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:22300
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0

# Replication
role:master
connected_slaves:3
slave0:ip=10.254.10.1,port=16378,state=online,offset=3578560662,lag=1
slave1:ip=10.254.10.2,port=16378,state=online,offset=3578536873,lag=1
slave2:ip=172.21.10.2,port=16378,state=online,offset=3578547805,lag=1
master_replid:882977534a40f1eaed577232abf0ab6d6f3a4e87
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:3578574419
second_repl_offset:-1
repl_backlog_active:1
repl_backlog_size:1048576
repl_backlog_first_byte_offset:3577525844
repl_backlog_histlen:1048576

# CPU
used_cpu_sys:898.240000
used_cpu_user:1857.540000
used_cpu_sys_children:259.636000
used_cpu_user_children:566.956000
server_threads:1
long_lock_waits:0

# Cluster
cluster_enabled:0

# Keyspace
db0:keys=16801,expires=917,avg_ttl=537232911

127.0.0.1:6375> hset test:test 10000 1
(integer) 1
127.0.0.1:6375> hset test:test 20000 1
(integer) 1
127.0.0.1:6375> hset test:test 30000 1
(integer) 1
127.0.0.1:6375> hset test:test 40000 1
(integer) 1
127.0.0.1:6375> hset test:test 50000 1
(integer) 1
127.0.0.1:6375> hset test:test 60000 1
(integer) 1
127.0.0.1:6375> hset test:test 70000 1
(integer) 1
127.0.0.1:6375> hset test:test 80000 1
(integer) 1
127.0.0.1:6375> hset test:test 86400 1
(integer) 1
127.0.0.1:6375> expiremember test:test 10000 10000
(integer) 1
127.0.0.1:6375> expiremember test:test 20000 20000
(integer) 1
127.0.0.1:6375> expiremember test:test 30000 30000
(integer) 1
127.0.0.1:6375> expiremember test:test 40000 40000
(integer) 1
127.0.0.1:6375> expiremember test:test 50000 50000
(integer) 1
127.0.0.1:6375> expiremember test:test 60000 60000
(integer) 1
127.0.0.1:6375> expiremember test:test 70000 70000
(integer) 1
127.0.0.1:6375> expiremember test:test 80000 80000
(integer) 1
127.0.0.1:6375> expiremember test:test 86400 86400
(integer) 1
127.0.0.1:6375> ttl test:test 10000
(integer) 9927
127.0.0.1:6375> ttl test:test 86400
(integer) 86373
127.0.0.1:6375> HKEYS test:test
1) "10000"
2) "20000"
3) "30000"
4) "40000"
5) "50000"
6) "60000"
7) "70000"
8) "80000"
9) "86400"

after 2 days

127.0.0.1:6375> hgetall test:test
 1) "50000"
 2) "1"
 3) "60000"
 4) "1"
 5) "70000"
 6) "1"
 7) "80000"
 8) "1"
 9) "86400"
10) "1"
127.0.0.1:6375> ttl test:test 50000
(integer) -1

**Comment by JohnSully** [comment] 2020-03-19 20:07
Possibly related to #155.  Looks like there's a gremlin in the subkey expire datastructure.

**Comment by JohnSully** [comment] 2020-03-25 05:15
Not a dupe, but I do have a repro.  Target for this fix is v5.3.3

**Comment by JohnSully** [comment] 2020-03-25 05:35
This is a regression from change 06ad1c15d

**Comment by JohnSully** [comment] 2020-03-25 05:40
OK This is fixed in change 528a43bd.  Fortunately the issue is in the load code so your RDB files are not corrupt.  The fix will be out in v5.3.3 in the next few days.  v5.3.1 is also not affected.

**Closed by JohnSully** 2020-03-25 05:40 UTC

**Comment by JohnSully** [comment] 2020-03-25 19:15
Round-trip persistence test added with change 4e572974
