### ISSUE TITLE
BITOP lshift string in tests/unit/bitops.tcl error

### ISSUE THREAD

**Issue by hezhiqiang** [JohnSully/KeyDB#117] opened 2019-12-10 06:46 UTC
when i make test on centos 7, there are some errors:

*** [err]: BITOP lshift string in tests/unit/bitops.tcl
Expected 'ïg' to equal or match 'abcdefg'
Cleanup: may take some time... OK
make[1]: *** [test] Error 1
make[1]: Leaving directory `/data/KeyDB-5.1.1/src'
make: *** [test] Error 2

**Comment by JohnSully** [comment] 2019-12-10 08:39
I think this is a dupe of: https://github.com/JohnSully/KeyDB/issues/99

Can you check if this repros in the unstable branch?  Its a test only issue related to the older TCL version on CentOS.

**Comment by hezhiqiang** [comment] 2019-12-10 11:42
i use the 5.1.1 release

**Comment by JohnSully** [comment] 2019-12-10 17:50
Then its a dupe as the fix hasn’t been released yet. This is a test only issue.

**Closed by JohnSully** 2019-12-10 17:50 UTC
