### ISSUE TITLE
Error when make

### ISSUE THREAD

**Issue by anyUesr** [JohnSully/KeyDB#10] opened 2019-03-15 03:18 UTC
just use `make`
```
make[3]: Leaving directory '/home/atn4517/KeyDB-0.9.2/deps/jemalloc'
make[2]: Leaving directory '/home/atn4517/KeyDB-0.9.2/deps'
    CC adlist.o
    CC quicklist.o
    CC ae.o
    CC anet.o
    CC dict.o
    CC server.o
In file included from server.cpp:31:0:
server.h:2331:68: error: declaration of ‘void* calloc(size_t, size_t)’ has a different exception specifier
 void *calloc(size_t count, size_t size) __attribute__ ((deprecated));
                                                                    ^
In file included from server.h:42:0,
                 from server.cpp:31:
/usr/include/stdlib.h:468:14: error: from previous declaration ‘void* calloc(size_t, size_t) throw ()’
 extern void *calloc (size_t __nmemb, size_t __size)
              ^
In file included from server.cpp:31:0:
server.h:2332:49: error: declaration of ‘void free(void*)’ has a different exception specifier
 void free(void *ptr) __attribute__ ((deprecated));
                                                 ^
In file included from server.h:42:0,
                 from server.cpp:31:
/usr/include/stdlib.h:483:13: error: from previous declaration ‘void free(void*) throw ()’
 extern void free (void *__ptr) __THROW;
             ^
In file included from server.cpp:31:0:
server.h:2333:54: error: declaration of ‘void* malloc(size_t)’ has a different exception specifier
 void *malloc(size_t size) __attribute__ ((deprecated));
                                                      ^
In file included from server.h:42:0,
                 from server.cpp:31:
/usr/include/stdlib.h:466:14: error: from previous declaration ‘void* malloc(size_t) throw ()’
 extern void *malloc (size_t __size) __THROW __attribute_malloc__ __wur;
              ^
In file included from server.cpp:31:0:
server.h:2334:66: error: declaration of ‘void* realloc(void*, size_t)’ has a different exception specifier
 void *realloc(void *ptr, size_t size) __attribute__ ((deprecated));
                                                                  ^
In file included from server.h:42:0,
                 from server.cpp:31:
/usr/include/stdlib.h:480:14: error: from previous declaration ‘void* realloc(void*, size_t) throw ()’
 extern void *realloc (void *__ptr, size_t __size)
              ^
Makefile:278: recipe for target 'server.o' failed
make[1]: *** [server.o] Error 1
make[1]: Leaving directory '/home/user/KeyDB-0.9.2/src'
Makefile:6: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by JohnSully** [comment] 2019-03-15 04:49
Hi can you let me know what operating system you are using?  Mac or Linux (and if linux which distro?

It looks like this is a conflict with a system header.  I'll try my best to reproduce it.

**Comment by JohnSully** [comment] 2019-03-15 05:30
I haven't been able to reproduce this issue - but I've committed a fix which I think should resolve it: a9e525c8

I'm creating a new issue to track fixing the underlying cause once I can reproduce the issue.

**Comment by anyUesr** [comment] 2019-03-15 06:25
I use this version: [https://github.com/JohnSully/KeyDB/archive/v0.9.2.tar.gz](https://github.com/JohnSully/KeyDB/archive/v0.9.2.tar.gz)

and this is my environment:
```
$ gcc --version
gcc (Debian 4.9.2-10+deb8u2) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ g++ --version
g++ (Debian 4.9.2-10+deb8u2) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ cat /etc/issue
Debian GNU/Linux 8 \n \l
```

**Comment by JohnSully** [comment] 2019-03-15 06:37
Thanks I will try Debian tomorrow. 

In the meantime the unstable branch should compile for you with my temporary fix. I have not tried with a GCC that old but it does support C++14 so should work.

**Comment by JohnSully** [comment] 2019-03-20 01:24
I've verified Debian 8 (jessie) and confirmed it works.  

It did require one additional fix to ifdef out socket CPU pinning which is not available on older kernels.

**Closed by JohnSully** 2019-03-20 01:24 UTC
