### ISSUE TITLE
Count of threads depends from machine cores

### ISSUE THREAD

**Issue by MarcSky** [JohnSully/KeyDB#175] opened 2020-05-01 19:35 UTC
**Is your feature request related to a problem? Please describe.**
Hello everyone!
I using keydb for storing users sessions.
In past I using Redis but his was a very slow and very hard for cpu.
Now I using keydb 5.3.3 and I have only 1 core. I want to using 4-6 server-threads but I can't because when I setup `server-threads=4` I getting next message in my keydb logs - **"server-threads is greater than this machine's core count.  Truncating to 1 threads"** and this very sad and I don't understand what to do.

I understand that I can't using real multi-threads because I have only 1 core but maybe I can using concurrency ?) 

I using docker with keydb with next command 

    image: eqalpha/keydb:x86_64_v5.3.3
    command: keydb-server --appendonly yes --protected-mode no --server-threads 4
    ports:
      - '6379:6379'
    volumes:
      - app-db-keydb:/data

File keydb.conf not changed all in default configuration.

I really hope that I will be able to use this solution with more threads because its very important for my application speed. I notice that when many users use keydb at the same time, processing latency increase.

Thanks for help.

**Comment by JohnSully** [comment] 2020-05-01 19:38
Hi @MarcSky 

The reason for that limitation is using more threads then there are CPU cores will actually result in a speed decrease.  Unfortunately for KeyDB to make use of multiple threads there must be enough cores for each thread.

**Comment by MarcSky** [comment] 2020-05-01 19:51
@JohnSully thank you for quickly answer.
I just was little bit confusing with parameter **server-thread-affinity** I thought that if he has flag true then my thread will unpin from core.

> Should KeyDB pin threads to CPUs? By default this is disabled, and KeyDB will not bind threads.

**Comment by JohnSully** [comment] 2020-05-01 19:53
Even without thread pinning you still should have at least as many cores as threads.  This is because internally KeyDB uses a spinlock to ensure performance.  However if there are fewer cores than threads than spinning threads will steal CPU time from threads with real work to do.  This will result in a substantial decrease in performance.

**Comment by MarcSky** [comment] 2020-05-01 19:56
@JohnSully Okey I understand. Thank you ;)

**Comment by JohnSully** [comment] 2020-05-01 19:59
Closing as by design.

**Closed by JohnSully** 2020-05-01 19:59 UTC

**Comment by MarcSky** [comment] 2020-05-06 06:57
@JohnSully I found the solution of my problem. Keydb is really quickly but I doesn't close connection with him and I got memory leak. I noticed that when my app working long time my RAM going down.
Now I closing connection with keydb and grpc server and all good. Thanks.
